clientIO/joint

plugins/routers/joint.routers.manhattan.js

Routed links with vertices #123

---

src/core.js

Fix missing Math in core.js prefix.

---

CHANGELOG
src/geometry.js
src/joint.dia.element.js
src/joint.dia.graph.js
src/joint.dia.link.js
test/geometry/geometry.js
test/jointjs/basic.js
test/jointjs/graph.js

dia.Element: add scale() method
dia.Link: add scale() method
dia.Graph: add resizeCells() method

Geometry: add scale(), toJSON() methods

---

plugins/shapes/joint.shapes.basic.js

Fixes for IE in TextBlock shape (updating content).

Using new feature detection (foreignobject) in TextBlock shape

---

plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js
src/joint.dia.cell.js
src/joint.dia.element.js
src/joint.dia.graph.js
test/jointjs/basic.js

Implemented enhancement #239 with unit test for to-front and to-back  

---

package.json
scripts/postinstall.js

Fix for running `npm install` in production node environment

---

src/joint.dia.link.js

Fix for "TypeError: Failed to execute 'getPointAtLength' on 'SVGPathElement': The provided float value is non-finite." after label adding

Fix for TypeError

---

src/joint.dia.paper.js
test/jointjs/paper.js

Not ready for merge. There is an outstanding issue with normalizing dataURL in PhantomJS (possibly related to [this](https://github.com/ariya/phantomjs/issues/10455)).

dia.Paper: grid background takes scale into account

---

CHANGELOG
src/vectorizer.js
test/vectorizer/vectorizer.js

Refactored Vectorizer library. Everything is now testable.
Added V.prototype.empty() method.

Vectorizer spring cleaning

---

plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js
test/jointjs/coverage.html
test/jointjs/index.html
test/jointjs/plugins/layout/DirectedGraph.js

Some minor refactoring and added tests (there were none).

RAP-821: Can now layout an array of cells instead of the full graph.

---

src/vectorizer.js
test/vectorizer/index.html
test/vectorizer/vectorizer.js

RAP-867 - vectorizer - remove attribute

---

CHANGELOG
css/layout.css
css/themes/dark.css
css/themes/default.css
css/themes/material.css
css/themes/modern.css
demo/basic.html
demo/paper/paper.css
plugins/highlighters/joint.highlighters.addClass.js
plugins/highlighters/joint.highlighters.opacity.js
plugins/highlighters/joint.highlighters.stroke.js
plugins/shapes/joint.shapes.basic.js
plugins/shapes/joint.shapes.devs.js
plugins/shapes/joint.shapes.pn.js
src/core.js
src/joint.dia.cell.js
src/joint.dia.element.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/joint.mvc.view.js
test/jointjs/basic.js
test/jointjs/core/util.js
test/jointjs/mvc.view.js
test/jointjs/paper.js
wrappers/joint.foot.js

__Contains breaking changes.__
Shouldn't be merged until **after** the next 0.9.x release.

RAP-797: All classes used internally now given joint- class name prefix

---

src/joint.dia.element.js

Apply transitions on nested cells as well

fix transitions on embedded elements. 

---

src/joint.dia.element.js

Apply transitions on nested cells as well

Backport - fix transitions on embedded elements. 

---

src/vectorizer.js

fixed visibility of empty lines for FF

---

docs/src/joint/api/dia/Element/ports.md
docs/src/joint/api/dia/Element/prototype/portProp.md
src/joint.dia.element.js
src/joint.dia.paper.js
src/ports.js
test/jointjs/basic.js
test/jointjs/elementPorts.js

- portProp allows to set port properties by port id 
- added `data-group` attribute to the port DOM element 
ready @kumilingus

Create `portProp` method 

---

src/joint.dia.element.js

fix the z-index computing behaviour on embedded elements

z-index issue fix

---

plugins/highlighters/joint.highlighters.addClass.js
plugins/highlighters/joint.highlighters.opacity.js
plugins/highlighters/joint.highlighters.stroke.js
src/joint.dia.cell.js
test/jointjs/elementView.js

highlighters should manage empty options

dia.Paper: custom highlighter defaults options

---

src/core.js

core: imageToDataUri: fix images with urls pointing to a file or to a remote resource

---

docs/src/joint/api/dia/Link/prototype/presentation.html

router.manhattan: update docs

---

Gruntfile.js
docs/src/joint/api/util/imageToDataUri.html
plugins/polyfills/base64.js
plugins/polyfills/typedArray.js
plugins/polyfills/xhrResponse.js
src/core.js

@kumilingus ready! (except the docs)

util.imageToDataUri:  convert images using  xhr, not the canvas

---

docs/src/geometry/api/g/line/constructor.html
docs/src/joint/api/SpecialAttributes/fill.html
docs/src/joint/api/dia/Element/prototype/findView.html
docs/src/joint/api/dia/Graph/prototype/getFirstCell.html
docs/src/joint/api/dia/Graph/prototype/getLastCell.html
docs/src/joint/api/dia/Link/prototype/findView.html
docs/src/joint/api/dia/Link/prototype/presentation.html
docs/src/joint/api/dia/Paper/prototype/options/async.html
docs/src/joint/api/dia/Paper/prototype/options/markAvailable.html
docs/src/vectorizer/api/prototype/animateAlongPath.html
docs/src/vectorizer/api/prototype/text.html

Docs: fix links

---

bower.json

exclude everything but dist folder in bower file

---

src/core.js
test/jointjs/core/util.js

core: jquery 3.1: getElementBbox compatible with jquery 3.1

---

README.md
demo/hull/src/hull.js
demo/pipes.js
docs/src/geometry/api/g/ellipse/prototype/inflate.html
docs/src/geometry/api/g/rect/prototype/inflate.html
src/geometry.js
test/geometry/ellipse.js
test/geometry/rect.js

- rect.inflate()
- ellipse.inflate()
- tests

Geometry: add `rect.inflate`

---

css/layout.css
demo/paper/css/paper.css
demo/paper/index.html
demo/paper/src/paper.js
docs/src/joint/api/dia/Paper/prototype/drawBackground.md
docs/src/joint/api/dia/Paper/prototype/options/background.md
src/joint.dia.paper.js
test/jointjs/paper.js

dia.Paper: add background option

---

docs/src/geometry/api/g/line/prototype/intersect.html
docs/src/geometry/api/g/line/prototype/intersection.html
docs/src/geometry/api/g/point/prototype/difference.html
docs/src/geometry/api/g/point/prototype/offset.html
docs/src/geometry/api/g/rect/prototype/bottomLine.html
docs/src/geometry/api/g/rect/prototype/leftLine.html
docs/src/geometry/api/g/rect/prototype/rightLine.html
docs/src/geometry/api/g/rect/prototype/topLine.html
src/geometry.js
test/geometry/line.js
test/geometry/point.js
test/geometry/rect.js

JIRA: RAP-940
@kumilingus Please review.

Geometry: additional API, improvements

---

src/core.js
src/joint.dia.cell.js
src/ports.js
test/jointjs/cell.js
test/jointjs/core/util.js
test/jointjs/elementPorts.js

dia.Cell: prop(), removeProp() should accept path defined as an array

---

demo/paper/index.html
demo/paper/src/paper.js
docs/css/api.css
docs/src/joint/api/dia/Paper/prototype/options/drawGrid.html
src/joint.dia.paper.js

dia.Paper: add a new grid type: fixedDot

---

docs/demo/dia/Paper/interactive/addLinkFromMagnet.html
docs/demo/dia/Paper/interactive/arrowheadMove.html
docs/demo/dia/Paper/interactive/elementMove.html
docs/demo/dia/Paper/interactive/enableAll.html
docs/demo/dia/Paper/interactive/labelMove.html
docs/demo/dia/Paper/interactive/useLinkTools.html
docs/demo/dia/Paper/interactive/vertexAdd.html
docs/demo/dia/Paper/interactive/vertexMove.html
docs/demo/dia/Paper/interactive/vertexRemove.html
docs/src/joint/api/dia/Paper/prototype/options/interactive.html

dia.LinkView: document all interactive options and label position

---

src/vectorizer.js
test/vectorizer/vectorizer.js

Vectorizer: fix matrixToTransformString 

---

types/joint.d.ts

added missing Link/LinkView support for paper.findView and
paper.findViewByModel

add LinkView supp for findView and findViewByModel

---

Gruntfile.js

make watch task significantly faster on windows

Grunt: watch options

---

types/joint.d.ts

PR to fix TypeScript error in #605

Update restrictTranslate type.

---

css/layout.css

Reverts clientIO/joint#610
accidentally merged 2.0 feature

Revert "dia.ElementView: apply vector-effect: non-scaling-stroke to nodes ins…"

---

demo/layout/index.html
demo/layout/src/layout.js
docs/src/geometry/api/g/line/prototype/closestPoint.html
docs/src/geometry/api/g/line/prototype/closestPointNormalizedLength.html
docs/src/geometry/api/g/line/prototype/vector.html
docs/src/geometry/api/g/point/prototype/dot.html
docs/src/geometry/api/g/point/prototype/squaredDistance.html
docs/src/joint/api/layout/DirectedGraph.html
plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js
src/geometry.js
src/joint.dia.link.js
test/geometry/line.js
test/geometry/point.js
test/jointjs/links.js
types/geometry.d.ts

**layout.DirectedGraph** - take label metrics into account, position labels
**Geometry** - add `dot`, `squaredDistance` to Point
**Geometry** - add `closestPoint`, `closestPointNormalizedLenght`, `vector` to Line
**Geometry** - fix `g.Line.prototype.clone()`
**Layout demo** - add new demo
**dia.LinkView** - optimize on change labels handler

layout.DirectedGraph: take the label metrics into account, position labels

---

demo/ts-demo/tsconfig.json
types/joint.d.ts

remove private methods from definition files

TS def: typescript definition cleanup 

---

docs/src/joint/api/dia/Paper/prototype/options/moveThreshold.html
src/joint.dia.paper.js
test/jointjs/paper.js

dia.Paper: `moveThreshold` option

---

docs/src/joint/api/dia/LinkView/prototype/sendToken.html
src/joint.dia.link.js
src/vectorizer.js

LinkView: sendToken allows to send token backwards, fix token flashing

---

plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js
plugins/routers/joint.routers.manhattan.js
plugins/routers/joint.routers.metro.js
src/core.js
src/joint.dia.cell.js
src/joint.dia.element.js
src/joint.dia.graph.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/joint.mvc.view.js
src/ports.js

 Remove Lodash: _isFunction, _result, _union, _invoke, _constant

---

plugins/routers/joint.routers.orthogonal.js
plugins/shapes/joint.shapes.basic.js
src/joint.dia.graph.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/ports.js

use native Array.filter, Array.map

Remove Lodash: _filter, _map

---

plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js
plugins/shapes/joint.shapes.basic.js
src/core.js
src/joint.dia.attributes.js
src/joint.dia.cell.js
src/joint.dia.graph.js
src/joint.dia.paper.js
src/ports.js

_pick - alias 
_omit - alias 
_keys - Object.keys
_isPlainObjectAlias

Remove Lodash: _.keys, _isPlainObject, _omit, _pick

---

plugins/connectors/joint.connectors.jumpover.js
plugins/layout/ports/joint.layout.port.js
plugins/routers/joint.routers.orthogonal.js
plugins/shapes/joint.shapes.devs.js
src/core.js
src/joint.dia.cell.js
src/joint.dia.graph.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/ports.js

Remove Lodash: _contains, _map 

---

docs/src/joint/api/dia/Paper/prototype/options/preventContextMenu.html
docs/src/joint/api/dia/Paper/prototype/options/preventDefaultBlankAction.html
src/joint.dia.paper.js

dia.Paper: add preventDefaultBlankAction option

---

src/core.js
src/joint.dia.cell.js
src/joint.dia.graph.js
src/ports.js
test/jointjs/elementPorts.js

Remove lodash: remove - _reject, alias - _delay

---

types/joint.d.ts

so that the Paper class can properly have a Graph Model.

TS: make mvc.View generic 

---

demo/table.html
demo/table.js

https://codepen.io/vladimirtalas/pen/MrymjB

joint.shapes.basic.Table

---

src/joint.dia.graph.js
test/jointjs/graph.js

dia.Graph: getCellsBBox() takes the cells rotation into account

---

.eslintrc.js
demo/basic.js
demo/petri nets/src/smil.user.js
plugins/anchors/joint.anchors.js
plugins/connectionPoints/joint.connectionPoints.js
plugins/connectionStrategies/joint.connectionStrategies.js
plugins/polyfills/number.js
plugins/routers/joint.routers.manhattan.js
plugins/tools/joint.linkTools.js
src/core.js
src/geometry.js
src/joint.dia.attributes.js
src/joint.dia.cell.js
src/joint.dia.element.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/ports.js
src/vectorizer.js
test/geometry/line.js
test/geometry/path.js
test/geometry/point.js
test/jointjs/cell.js
test/jointjs/core/util.js
test/jointjs/dia/attributes.js
test/jointjs/elementPorts.js
test/jointjs/linkView.js
test/jointjs/links.js
test/jointjs/paper.js

- Update FakeSmile lib for Petri nets demo
- Semicolons

Various minor fixes

---

src/joint.dia.element.js

Fix arguments for backward compatibility
See #1040

Update joint.dia.element.js for correct backward compatibility

---

src/joint.dia.cell.js
src/ports.js
types/joint.d.ts

dia.Cell: add generateId(); dia.Element: generatePortId()

---

plugins/shapes/joint.shapes.basic.js
plugins/shapes/joint.shapes.devs.js
src/geometry.js
src/graph.js
src/joint.dia.attributes.js
src/joint.dia.link.js
src/joint.dia.paper.js
src/joint.dia.tools.js
src/joint.mvc.view.js
src/util.js
src/vectorizer.js

Fixing several typos and misspellings in the doc comments
Should I run anything to regenerate the dist/docs folder or wait for a release at a later point?

(Docs) nit fix typos in comments

---

package-lock.json
package.json

Upgrade jQuery, Backbone, Graphlib, Dagre

---

src/V/index.mjs
src/dia/Paper.mjs

* dia.Paper - fix method name typo

Vectorizer: fix svgCreateDocument for IE11

---

src/dia/LinkView.mjs
src/routers/manhattan.mjs

ES6: fix imports in manhattan router 

---

docs/src/joint/api/dia/Paper/prototype/cancelRenderViews.html
types/joint.d.ts

Fix https://github.com/clientIO/joint/issues/1161.

dia.Paper: remove cancelRenderViews() leftover from docs and TS

---

types/joint.d.ts

Fix https://github.com/clientIO/joint/issues/1165

dia.Cell: fix TS definition for remove() options

---

grunt/resources/esm.js
package-lock.json
package.json
rollup.resources.js

Rollup: Fix ES5  dependencies 

---

docs/src/geometry/api/g/Polyline/prototype/length.html
docs/src/geometry/api/g/Polyline/prototype/simplify.html
src/dia/LinkView.mjs
src/g/index.mjs
src/layout/DirectedGraph/DirectedGraph.mjs
test/geometry/polyline.js
types/geometry.d.ts

g.Polyline: simplify() (remove redundant vertices)

---

src/connectors/jumpover.mjs

This PR extract and modify code from rounded connector to support rounded corner for jumpover connector.

connectors.jumpover: add radius option

---

package.json

Fix for https://github.com/clientIO/joint/issues/1276

Upgrade jQuery dependency

---

src/dia/CellView.mjs
src/dia/LinkView.mjs

Fixes https://github.com/clientIO/joint/issues/1270.

dia.LinkView: fix never ending batch for legacy link tools

---

docs/demo/dia/Paper/interactive/labelMoveSnapLabels.html
docs/src/joint/api/dia/Paper/prototype/options/interactive.html
docs/src/joint/api/dia/Paper/prototype/options/snapLabels.html
src/dia/LinkView.mjs
src/dia/Paper.mjs
tutorials/js/link-labels-interaction-snap-labels.js
tutorials/js/link-labels-interaction.js
tutorials/link-labels.html
types/joint.d.ts

Paper: snapLabels option

---

tutorials/installation.html

Tutorial: update dependecies

---

src/dia/ElementView.mjs
src/dia/LinkView.mjs
types/joint.d.ts

Replace string flag values with an enum and make the enum accessible on the class.

dia.ElementView, dia.LinkView: expose presentation attributes flags (#1486)

---

tutorials/custom-attributes.html

- updated with 'overwriting with prop()' section using `{ rewrite: true }`
- updated with 'element.toJSON()' output

tutorials: add custom attributes tutorial

---

docs/src/joint/api/dia/Element/prototype/prop.html
docs/src/joint/api/dia/Link/prototype/prop.html

- updated with similar example like custom attributes tutorial

dia.Link,dia.Element: add prop rewrite option to docs

---

.gitignore

- update with files generated during `grunt test`; they should be ignored

gitignore: update with files generated during grunt test

---

.gitignore
package.json

```
npm notice 📦  jointjs@3.4.2
npm notice === Tarball Contents ===
npm notice 39.9kB  CHANGELOG
npm notice 16.8kB  LICENSE
npm notice 1.3kB   css/themes/dark.css
npm notice 1.2kB   css/themes/default.css
npm notice 50.4kB  dist/joint.core.css
npm notice 46.3kB  dist/joint.core.min.css
npm notice 50.4kB  dist/joint.css
npm notice 46.3kB  dist/joint.min.css
npm notice 4.1kB   css/layout.css
npm notice 42.4kB  css/themes/material.css
npm notice 1.1kB   css/themes/modern.css
npm notice 154B    src/polyfills/array.js
npm notice 2.8kB   src/polyfills/base64.js
npm notice 205.0kB dist/geometry.js
npm notice 58.8kB  dist/geometry.min.js
npm notice 61B     index.js
npm notice 991.3kB dist/joint.core.js
npm notice 335.1kB dist/joint.core.min.js
npm notice 1.1MB   dist/joint.js
npm notice 12.8kB …
```

Whitelist files for NPM publish

---

demo/list/.gitignore
demo/list/index.html
demo/list/package.json
demo/list/src/index.ts
demo/list/tsconfig.json
demo/list/webpack.config.js

demo.List: element with vertical list of items

---

tutorials/connecting-by-dropping.html
tutorials/constraint-move-to-circle.html
tutorials/hierarchy.html
tutorials/html-elements.html
tutorials/links-patterns.html
tutorials/ports.html
tutorials/requirejs.html
tutorials/ts-shape.html

- add general disclaimer to archive tutorials (ports tutorial has specific note too)
- fix code block spacing in custom TypeScript shape tutorial

tutorials: add archive tutorial disclaimer

---

test/ts/index.test.ts
types/joint.d.ts

Implements https://github.com/clientIO/joint/issues/1418.

dia.Paper: add type definition for event handlers

---

types/joint.d.ts

types: add Port and PortLabel layout types

---

docs/src/joint/api/dia/Cell/markup.html
docs/src/joint/api/dia/Element/intro.html
docs/src/joint/api/dia/Link/intro.html

docs: improve explanation of attributes placement

---

docs/src/joint/api/dia/Element/ports.md
src/dia/ports.mjs
test/jointjs/elementView.js

dia.ElementView: allow ports without labels

---

docs/demo/dia/Element/js/portZIndex.js
docs/demo/dia/Element/portZIndex.html
docs/src/joint/api/dia/Element/ports.md
tutorials/js/ports-basic.js

- update markup examples with JSON markup
- update related demo

dia.Element.ports: update docs markup examples

---

demo/curves/css/curves.css
demo/curves/index.html
demo/curves/src/curves.js
src/dia/LinkView.mjs
src/linkTools/index.mjs
test/jointjs/linkView.js

- **demo.Curves** - a new demo with curve connector
- **dia.Paper** - improve `connectionStrategy` with `snapLinks` enabled
- **linkTools.Connect** - check `mouseleave` event after the user creates a new connection

Curves Connector Demo

---

demo/ts-demo/package.json

demo.TsDemo: upgrade backbone types

---

demo/.eslintrc.js
demo/marey/css/marey.css
demo/marey/index.html
demo/marey/src/marey.js

- wasn't sure if you wanted this PR. JointJS_Site PR has a link to src code, so I can remove the link if necessary.
- update eslint to support class properties which we use in this demo

demo: add Marey Chart demo

---

src/dia/Paper.mjs

Fixes https://groups.google.com/g/jointjs/c/_iJ8ZDXCdsE/m/qacgPXDpBgAJ.

dia.Paper: make sure paper:mouseenter event is always triggered

---

docs/src/joint/api/util/getRectPoint.html
src/dia/Graph.mjs
src/util/getRectPoint.mjs
src/util/index.mjs
test/jointjs/core/util.js
types/joint.d.ts

Unify the way to search for points on rectangles using keywords in different parts of the library.

util.getRectPoint: add utility to get a point on a rect from given keyword

---

types/joint.d.ts

- similar to https://github.com/clientIO/joint/pull/1730

types: allow passing generic attributes to elements

---

.github/ISSUE_TEMPLATE/bug.yml
.github/pull_request_template.md

- update browsers in Issue_Template (add opera, android, iOS)
Editor after creating new PR:
Preview of Template:

chore: add github PR template

---

demo/sequence/index.html
demo/sequence/src/joint.shapes.sd.js
demo/sequence/src/sequence.js
docs/src/joint/api/elementTools/Connect.html
docs/src/joint/api/elementTools/HoverConnect.html
docs/src/joint/api/linkTools/Connect.html
docs/src/joint/api/linkTools/HoverConnect.html
src/elementTools/HoverConnect.mjs
src/elementTools/index.mjs
src/linkTools/Button.mjs
src/linkTools/HoverConnect.mjs
src/linkTools/index.mjs
test/ts/toolsView.test.ts
types/joint.d.ts

- add a new tool to show the connect button at the position of the mouse cursor
- add editing capabilities to **sequence** demo.

linkTools, elementTools: add HoverConnect tool

---

types/joint.d.ts

Revert "types: allow passing generic attributes to elements"

---

demo/icons/index.html
demo/icons/src/icons.js
docs/src/joint/api/dia/HighlighterView/prototype/UPDATE_ATTRIBUTES.html
docs/src/joint/api/highlighters/list.html
src/dia/HighlighterView.mjs
src/highlighters/index.mjs
src/highlighters/list.mjs
src/util/getRectPoint.mjs
src/util/index.mjs
test/jointjs/dia/HighlighterView.js
test/ts/index.test.ts
types/joint.d.ts

highlighters: add List

---

docs/src/joint/api/mvc/Listener.html
package.json
src/mvc/index.mjs
test/jointjs/index.html
test/jointjs/lodash3/index.html
test/jointjs/mvc.listener.js
test/ts/mvc.listener.test.ts
types/joint.d.ts

Added Listener class, tests, types, and docs.

mvc.Listener

---

src/util/util.mjs

Fix horizontal scrolling on windows/linux

fix(util): horizontal scroll with shift

---

types/joint.d.ts

Define `style` attribute in TS

mvc.View: add style attribute type

---

.github/workflows/codeql.yml
test/jointjs/core/util.js

Analyze code using CodeQL and display the results as code scanning alerts.

Add CodeQL Security Analysis

---

src/util/util.mjs
test/jointjs/core/util.js

Fix freezing when preserving spaces on textWrap.

util.breakText: fix preserveSpaces

---

docs/src/joint/api/dia/ElementView/prototype/hasTools.html

Add missing `hasTools` documentation
Fixes #1869

docs(dia.ElementView): add hasTools

---

package.json

- update keywords list (changed to a single line because it's less annoying than scrolling a long list)

chore: update keywords in package.json

---

docs/src/joint/api/dia/Element/prototype/embed.html

- add `embed` options description 
Fixes #1906

docs(dia.Element): add embed options description

---

.vscode/settings.json
tutorials/css/tutorial.css

- style `li` tags the same as `p` tags in `tutorial.css`

docs(tutorials): update tutorial styles

---

src/dia/ElementView.mjs
test/jointjs/elementPorts.js

Addresses issue no. 1 from https://github.com/clientIO/joint/issues/2026#issuecomment-1422185153

fix(dia.ElementView): fix number of port updates

---

.github/DISCUSSION_TEMPLATE/q-a.yml

- improve github discussion template formatting

chore(github): improve discussion template formatting

---

docs/src/joint/api/dia/Paper/prototype/options/overflow.html
src/dia/Paper.mjs
types/joint.d.ts

Add an option to paper which allows cells to overflow paper. Updated documentation.

feat(dia.Paper): add overflow option

---

demo/ports/port-layouts-labels.js
docs/src/joint/api/dia/Element/ports.md
src/dia/ports.mjs
src/layout/ports/portLabel.mjs

Addresses issue no. 3 from https://github.com/clientIO/joint/issues/2026#issuecomment-1422185153

fix(layout.PortLabel): make sure layout attributes are always applied to text element

---

types/joint.d.ts

Fixed typo in `transformToFitContentOptions`

types(dia.Paper): types typo

---

.github/workflows/stale.yml

- replace `new feature` tag with `candidate feature`

chore(github): update stale action tags

---

demo/isometric/src/utils.ts

Fixed z-index sorting algorithm (but new version has an increased complexity). The algorithm is found [here](https://mazebert.com/forum/news/isometric-depth-sorting--id775/) and it is implementation of [topological sorting](https://en.wikipedia.org/wiki/Topological_sorting) algorithm with a depth first search.

fix(demo.Isometric): fix z-index sorting algorithm

---

demo/ts-demo/package.json

Update dependencies of `ts-demo`
- update `jointjs` dependencies
- bring `TS` and `webpack` dependencies into sync with versions used in `joint`, `rappid` and `app` template

chore(demo.ts-demo): update demo dependencies

---

src/dia/attributes/index.mjs

fix(dia.attributes): fix ambiguous order of cache keys in text attribute

---

packages/joint-core/docs/src/joint/api/mvc/Collection/prototype/find.html
packages/joint-core/docs/src/joint/api/mvc/Collection/prototype/findIndex.html
packages/joint-core/src/mvc/Collection.mjs
packages/joint-core/types/joint.d.ts

Add `find()` and `findIndex()` methods to `mvc.Collection.prototype`.

feat(mvc.Collection): add find() and findIndex()

---

README.md
examples/decorators/README.md
examples/dwdm/README.md
examples/fta-js/README.md
examples/isometric/README.md
examples/layout-directed-graph/README.md
examples/list/README.md
examples/shapes-general/README.md
examples/tree-of-life/README.md
packages/joint-core/README.md
packages/joint-core/demo/custom-embedding/README.md
packages/joint-core/demo/custom-shapes/README.md
packages/joint-core/demo/elk/README.md
packages/joint-core/demo/rough/README.md
packages/joint-core/demo/tree-shake/README.md
packages/joint-core/demo/ts-demo/README.md
packages/joint-core/demo/vuejs/README.md
packages/joint-decorators/README.md
packages/joint-layout-directed-graph/README.md
packages/joint-shapes-general-tools/README.md
packages/joint-shapes-general/README.md

Update copyright year: 2023 => 2024

chore: update year

---

CHANGELOG
examples/decorators/package.json
examples/dwdm/package.json
examples/fta-js/package.json
examples/isometric/package.json
examples/layout-directed-graph/package.json
examples/list/package.json
examples/shapes-general/package.json
examples/tree-of-life/package.json
package.json
packages/joint-core/demo/custom-shapes/package.json
packages/joint-core/demo/elk/package.json
packages/joint-core/demo/rough/package.json
packages/joint-core/demo/tree-shake/package.json
packages/joint-core/demo/ts-demo/package.json
packages/joint-core/demo/vuejs/package.json
packages/joint-core/package.json
packages/joint-decorators/package.json
packages/joint-layout-directed-graph/package.json
packages/joint-shapes-general-tools/package.json
packages/joint-shapes-general/package.json
yarn.lock

- adds missing `src/core.mjs` in the `dist` folder.
- change the '@joint/layout-directed-graph` constraint on `@joint/core` dependency

Release v4.0.1

---

packages/joint-core/src/routers/rightAngle.mjs
packages/joint-core/test/jointjs/routers.js

Remove unnecessary points and loops from the right-angle router's route.
Improve the overall generated route and code quality.
Long awaited right angle router improvements.

fix(routers.RightAngle): route improvements

---

examples/libavoid/.gitignore
examples/libavoid/README.md
examples/libavoid/index.html
examples/libavoid/index.js
examples/libavoid/package.json
examples/libavoid/src/app.js
examples/libavoid/src/avoid-router.js
examples/libavoid/src/resize-tool.js
examples/libavoid/src/shapes.js
examples/libavoid/styles.scss
examples/libavoid/webpack.config.js
yarn.lock

Add an example of how to integrate [libavoid-js](https://github.com/Aksem/libavoid-js) library with *JointJS* to route the links.

feat(examples.libavoid): add orthogonal routing demo

---

packages/joint-core/types/joint.d.ts

Adds `dia.DiagonalDirection` type, a subset of `dia.Direction`. This type is useful for JJ+ `ui.FreeTransform` plugin.

types(dia): add DiagonalDirection type

---

packages/joint-core/types/joint.d.ts

Fixes missed properties from documentation

types(dia.LinkView): fixes properties typings

---

packages/joint-core/types/joint.d.ts

Exposes the `util.cloneCell()` method.

feat(util): expose cloneCells() method

---

packages/joint-core/src/util/utilHelpers.mjs

Remove unused function arguments in `utilHelpers`.

chore(utilHelpers): fix code quality

---

packages/joint-core/demo/hull/src/hull.js
sonar-project.properties

- do not analyze 3rd party code: `garbochess.js`, `polyfills`  _(should be installed via package manager)_
- do not check code duplicities in tests and examples
- prefer use of built-in `g.random` utility over a custom code in _hull_ example

chore: update sonar qube config

---

CHANGELOG
examples/decorators/package.json
examples/dwdm/package.json
examples/fta-js/package.json
examples/isometric/package.json
examples/layout-directed-graph/package.json
examples/libavoid/package.json
examples/link-labels-ts/package.json
examples/list/package.json
examples/shapes-general/package.json
examples/tree-of-life/package.json
package.json
packages/joint-core/demo/custom-shapes/package.json
packages/joint-core/demo/elk/package.json
packages/joint-core/demo/rough/package.json
packages/joint-core/demo/tree-shake/package.json
packages/joint-core/demo/ts-demo/package.json
packages/joint-core/demo/vuejs/package.json
packages/joint-core/package.json

* **mvc.Listener** - fix to support running in Web Workers (12b0c32b)

Release v4.1.2

---

CHANGELOG
examples/decorators/package.json
examples/dwdm/package.json
examples/fta-js/package.json
examples/isometric/package.json
examples/layout-directed-graph/package.json
examples/libavoid/package.json
examples/link-labels-ts/package.json
examples/list/package.json
examples/shapes-general/package.json
examples/tree-of-life/package.json
package.json
packages/joint-core/demo/custom-shapes/package.json
packages/joint-core/demo/elk/package.json
packages/joint-core/demo/rough/package.json
packages/joint-core/demo/tree-shake/package.json
packages/joint-core/demo/ts-demo/package.json
packages/joint-core/demo/vuejs/package.json
packages/joint-core/package.json
packages/joint-decorators/package.json
packages/joint-layout-directed-graph/package.json
packages/joint-shapes-general-tools/package.json
packages/joint-shapes-general/package.json

* **mvc.Dom** - use `getComputedStyle` for static position check (1eff27a3)

Release v4.1.3

---

packages/joint-core/src/dia/Paper.mjs
packages/joint-core/src/dia/PaperLayer.mjs
packages/joint-core/src/dia/layers/GridLayer.mjs
packages/joint-core/test/jointjs/dia/Paper.js
packages/joint-core/test/jointjs/dia/PaperLayer.js
packages/joint-core/test/jointjs/index.html
packages/joint-core/types/joint.d.ts

An API to add / remove / change stacking order of paper layers.

feat(dia.Paper): layers API

---

packages/joint-layout-directed-graph/rollup.config.mjs

Use direct import with import assertion instead of fs.

chore: update import assert

---

packages/joint-react/src/components/graph-provider/graph-provider.test.tsx
packages/joint-react/src/components/graph-provider/graph-provider.tsx
packages/joint-react/src/components/paper/paper.test.tsx
packages/joint-react/src/data/create-store.test.ts

Add basics unit tests for `GraphProvider` and `Paper` to cover:
- proper links and elements rendering
- check if measured node succesfully working
- check if onElementsMeasured event is fired
- check if dynamically adding links and elements after load works
Clearly and concisely describe your changes in detail.
Cover at least simple scenarios of basic usage of new joint-react, there are plenty tests we should implement, so this is just start.

feat(joint-react): add basics missing unit test

---

examples/anchors-ts/README.md
examples/connection-points-ts/src/index.ts
examples/offscreen-rendering/.gitignore
examples/offscreen-rendering/README.md
examples/offscreen-rendering/index.html
examples/offscreen-rendering/package.json
examples/offscreen-rendering/src/index.ts
examples/offscreen-rendering/tsconfig.json
examples/offscreen-rendering/webpack.config.js
packages/joint-core/src/dia/CellView.mjs
packages/joint-core/src/dia/attributes/text.mjs
packages/joint-core/test/jointjs/dia/Paper.js
packages/joint-core/test/jointjs/dia/attributes.js
packages/joint-core/types/joint.d.ts
packages/joint-vitest-plugin-mock-svg/mocks/index.ts
yarn.lock

- **feat(dia.Paper):** add `measureNode()` option callback
- **feat(attributes):** fix the `text-wrap` attribute to work when the paper is not in the render tree
- **perf(dia.CellView):** - use cached bounding rect when measuring nodes referenced by the `ref` attribute
- **feat(offscreen-rendering):** add offscreen diagram rendering example
- **chore(examples):** :  update README of various examples
- **chore(joint-vitest-plugin-mock-svg):**:  mock `SVGElement.checkViewport()`

feat(dia.Paper): better offscreen rendering support

---

sonar-project.properties

Update the `sonar-cube` configuration to exclude examples from duplicated lines reporting.

chore: update sonar cube config
