clientIO/joint

src/joint.dia.element.js
src/joint.dia.link.js

Fixes batch:stop being called before the work in the batch is complete (in this case assigning link target on pointerup).
Makes link and element pointer events more uniform,  and corrects calls to batch:start and batch:stop

Fix issue with linkView poinermove and pointerup events being called before work is done.

---

package.json

Bower has a problem to find the version : 
bower ENORESTARGET  No tag found that was able to satisfy ~0.9.3
Additional error details:
No versions found in git://github.com/DavidDurman/joint.git

Changin the URL of the repository

---

bower.json

I added a "main" section so that things like wiredep can automatically wire-up the script/css tags in HTML to include the resources.

Add "main" section to bower.json to support build processes

---

bower.json

Hopefully this will fix (as MPL 2.0 is a valid license for bintray) webjars bower generation:
> Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at:  https://bintray.com/docs/api/#_footnote_1
> License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
>  Created Bower WebJar
> Fetched Bower zip
> Generated POM
> …

Added license

---

plugins/joint.shapes.basic.js

have getPortSelector return a selector to .port-body instead of circle.
This is compatable with the DEVS extension, but may break third party
code if they didn't copy over 'class="port-body" in their portMarkup.
Thoughts?

Allow ports with arbitrary markup

---

src/joint.dia.link.js

If a link has a Z order of 0, then after an arrowhead move the original z order will
be corrupted (set to Number.MAX_VALUE instead of back to 0). This was due to incorrect
logic [if(0), 0 evaluates to false in this case]. Replacing this with an undefined check
is the correct behavior to handle a 0 z order value.

Fixed bug where link z order is corrupt when previous state was 0 on head move

---

src/joint.dia.element.js

The code doesn't match the comment. It should try to get "markup" from the model first and fallback to the prototype.

Fix defaulting in `Element.renderMarkup()`

---

src/joint.dia.paper.js
test/jointjs/paper.js

Default paper.options.drawGrid to FALSE.
Don't draw grid lines if paper.options.gridSize is less than or equal to 1.

Backwards compatibility fixes for paper.drawGrid()

---

src/joint.dia.element.js

In this way it is possible to align an element w.r.t. the bottom or right of the parent.
Right now it is not possible and is required to use an y-alignment or x-alignment of  -0.9999999

Added support for y-alignment bottom and x-alignment right 

---

src/joint.dia.graph.js

Call sort just one time during toFront or toBack deep operations see issue #249

Avoid to call sort too much

---

Gruntfile.js
package.json

Fix for installing + using grunt-webpack in build process when using npm v3.
See #219

Unignoring webpack in node v5

---

src/vectorizer.js

@kumilingus ready for review 
set SVG attribute into correct namespace, otherwise some browsers might serialize svg document incorrecltly.
In Svg markup there will be attributtes with namespace defined e.g ```<a xlink:href="http://jointjs.com">...</a>```

set SVG attribute into correct namespace

---

Gruntfile.js

The issue only affected the minified version of Vectorizer.

RAP-845: Fix for white-space issue when using V.sanitizeText

---

package.json

To support requiring css like with [npm-css](https://www.npmjs.com/package/npm-css) to make it easier for people to consume the package when they are using npm for all the things instead of gulp/bower/grunt. I chose the minified css because i figured that's what most people would use in production.

Added style field  to package.json

---

plugins/connectors/joint.connectors.jumpover.js

When cells are reset, only the local variable got replaced and the old list of views was used in `updateJumpOver()`.
The symptoms were errors thrown on every `stop:batch` event resulting from missing `ownerSVGElement`s.

Fix jumpover on cells reset

---

plugins/highlighters/joint.highlighters.stroke.js
src/joint.dia.cell.js
src/joint.mvc.view.js
test/jointjs/mvc.view.js

@kumilingus Please review. I went with the methods on the view itself since they are called just once during initialization.

Override Backbone's _ensureElement and _setElement for an svg element view

---

src/joint.dia.paper.js
src/joint.mvc.view.js

- **dia.Paper** - `blank:pointerup` event is fired only after a preceeding `blank:pointerdown` event

dia.Paper: bind document events dynamically + minor cleanup

---

docs/src/joint/api/dia/Paper/prototype/clientOffset.html
docs/src/joint/api/dia/Paper/prototype/clientToLocalPoint.html
docs/src/joint/api/dia/Paper/prototype/clientToLocalRect.html
docs/src/joint/api/dia/Paper/prototype/localToClientPoint.html
docs/src/joint/api/dia/Paper/prototype/localToClientRect.html
docs/src/joint/api/dia/Paper/prototype/localToPagePoint.html
docs/src/joint/api/dia/Paper/prototype/localToPageRect.html
docs/src/joint/api/dia/Paper/prototype/localToPaperPoint.html
docs/src/joint/api/dia/Paper/prototype/localToPaperRect.html
docs/src/joint/api/dia/Paper/prototype/pageOffset.html
docs/src/joint/api/dia/Paper/prototype/pageToLocalPoint.html
docs/src/joint/api/dia/Paper/prototype/pageToLocalRect.html
docs/src/joint/api/dia/Paper/prototype/paperToLocalPoint.html
docs/src/joint/api/dia/Paper/prototype/paperToLocalRect.html
src/joint.dia.element.js
src/joint.dia.paper.js

- **dia.Paper** add `paperToLocalPoint()`,  `clientToLocalPoint()`, `pageToLocalPoint()`, `localToPaperPoint()`, `localToPagePoint()` and `localToClientPoint()`.
- **dia.Paper** add `paperToLocalRect()`, `clientToLocalRect()`, `pageToLocalRect()`, `localToPaperRect()`, `localToClientRect()` and `localToPageRect()`
- **dia.Paper** add `clientOffset()` and `pageOffset()`

dia.Paper: add convenient methods to convert coordinates

---

CHANGELOG
src/ports.js
test/jointjs/elementPorts.js

with only `change:ports` event it's hard to detect when ports are added or removed to the element.  
`add:port/remove:port` events provide the `cell` and array of added/removed elements
```
element.on('add:ports', function(cell, addedPorts) {
console.log("add port(s)", arguments);
});
element.on('remove:ports', function(cell, removecPorts) {
console.log("remove port(s)", arguments);
});
```

dia.Element.port: add:ports, remove:ports events proposal 

---

types/geometry.d.ts
types/joint.d.ts
types/vectorizer.d.ts

I had previously opened this with the DefinitelyTyped library (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15552). Just wanted to finish the type definitions for the geometry and vectorizer library here, since that version is deprecated.
Tested by building with grunt and compiling the build/joint.d.ts file with tsc -v == 2.2.1.

Complete typescript definitions for geometry and vectorizer utilities.

---

.gitignore
Gruntfile.js
package.json

Also fix for specifying browser for e2e tests like `grunt test:e2e:chrome`; was missing grunt-env module.
-------------------------
Run `rm -r node_modules/selenium-standalone && npm install` to re-install selenium-standalone. Then run:
```bash
grunt selenium
```
When selenium is finished installing you can run tests:
```bash
grunt test:e2e:chrome
```

Can now run e2e tests in Chrome; broken by some recent version of chrome

---

types/joint.d.ts

This adds some missing method definitions on the Cell, CellView, Element, ElementView, Link, LinkView, Graph, and Paper classes.
I've tried to clarify some of the options types that are passed into most method. I've switched uses of any over to object, since many of those uses were actually expecting an object type, not a number or string. Tested by building with grunt and compiling with tsc == 2.2.0

Flesh out joint.dia types. Clarify options on methods where I could understand them

---

types/geometry.d.ts

I've fixed the last implicit any errors in the `geometry.d.ts` file and updated the complete `joint.d.ts` file in the dist folder.
This pr closes #575

Fix typescript --noImplicitAny errors

---

types/joint.d.ts

This is now in line with the documentation described here: https://resources.jointjs.com/docs/jointjs/v1.1/joint.html#dia.Link.prototype.label
While the example only shows a `number` for position, it can actually be an object with distance and offset.

Fixes the allows label options in the TypeScript definitions.  

---

src/joint.dia.paper.js

https://github.com/clientIO/joint/issues/677
- When typeof cell is number, then error occurs... So I changed `paper.findViewByModel()`.
- I also make `paper.findViewByModel()` not throwing an exception when called with a falsy value.
~~- (We can use boolean values as a side effect... Shoud we check it?)~~
Please review this p-r :)

fix paper.findViewByModel()

---

package.json

So that things like 'object' are syntactically valid. They did not exists in 2.1.6.

Updates typescript dependency to the latest.

---

demo/ts-demo/custom.ts
demo/ts-demo/index.ts
demo/ts-demo/package.json
demo/ts-demo/tsconfig.json
types/joint.d.ts

- demostration of extending the `joint.shapes` namespace, using the `define` method. 
The problematic part is declaring a module. Is it possible to use the `define` without the declaration? 
```
declare module '../../build/joint' {
namespace shapes {
namespace app {
class CustomRect extends joint.shapes.basic.Rect {
test(): void;
static staticTest(): void;
}
}
}
}
```

TS: define, update ts demo 

---

src/joint.dia.link.js

it fixes wrong label text color in IE11 when the link is exported to PNG

dia.Link: set default font color for labels 

---

plugins/shapes/joint.shapes.basic.js

A bug was introduced which removed the "this.get" from before "('outPorts')".  This caused the outPorts to be returned as each letter of 'outPorts' rather than the outPorts themselves.

Fix to get correct outPorts

---

docs/src/joint/api/dia/Graph/prototype/maxZIndex.html
docs/src/joint/api/dia/Graph/prototype/minZIndex.html
src/joint.dia.cell.js
src/joint.dia.graph.js
src/joint.dia.paper.js
test/jointjs/basic.js
types/joint.d.ts

Two consecutive invocations of toFront or toBack produce a change in the
cells even though they already have the correct z values.
If the z values already satisfy the required order for toFront or toBack
they are not changed.
__Context:__
In an application I'm developing every time a user clicks on a cell i bring it to front, if the user starts clicking on the same cell over and over i get overwhelmed by `change:z` events.

Avoid to change z values during toFront or toBack

---

src/geometry.js
src/joint.dia.link.js

This fixes several errors of the form: `ReferenceError: assignment to undeclared variable router`

Use var to declare vars the first time they are used

---

docs/src/joint/api/dia/Element/ports.md
docs/src/joint/api/dia/Element/prototype/removePorts.md
src/ports.js
test/jointjs/elementPorts.js
types/joint.d.ts

Adding a new api to the Element prototype for batch removing ports.
This method will remove all of the specified ports (objects or portId strings) from the ports list before calling .prop().
This means a single .prop() call at the end of the batch which is much faster than removing them individually.
Additionally, it was strange that we had addPort/addPorts but only one removePort in the API.

Adding removePorts() to Element prototype

---

dist/joint.d.ts

TypeScipe declaration files are missing `CellView.InteractivityOptions` for dia.Paper.Options.interactive as possible return type if using a function.

dia.Paper.Options: add InteractivityOptions as function return type (Declaration files)

---

src/geometry.js
test/geometry/path.js

SVG supports this, and in some cases, V.normalizePathData() can produce almost-zero numbers that use scientific notation. This means that calling V.toGeometryShape() on a path can result in a V.normalizePathData() call that introduces scientific notation to the path, so without supporting scientific notation in the path parsing, the user can get an `e is not a recognized path segment type` error from deep inside joint code.

Support scientific notation in paths

---

src/vectorizer.js
test/vectorizer/vectorizer.js

The path normalizing code was not checking the radii for zero, and was ending up with NaN in path instructions in this case. W3C (https://www.w3.org/TR/SVG/paths.html#ArcOutOfRangeParameters) instructs user agents to treat it as a lineto in this case.

Fix normalizing paths with zero-radius arcs

---

package.json

By default webpack look for browser, module, main. It is desirable to use the dist for web builds.
Currently, jointjs blow up in ie 11 because it's using the mjs module entry point.

Add a browser key to point to dist

---

src/V/index.mjs
test/vectorizer/vectorizer.js

Fix https://github.com/clientIO/joint/issues/1178.

Vectorizer: fix e2c() overflowing the stack in normalizePathData()

---

types/joint.d.ts

The current return type when interactive is a function is `boolean`, but it can also be a `CellView.InteractivityOptions`.
Here is where it is used
https://github.com/clientIO/joint/blob/11a576dcacce1000ca4ee7104be880e66daaa2a5/src/dia/CellView.mjs#L175-L183
This fixes the typing so that an `CellView.InteractivityOptions` can be returned from the callback

types: fix interactive callback return type

---

types/joint.d.ts

Added an alias type `dia.Event`, using `JQuery.TriggeredEvent` instead of `JQuery.Event` for the callbacks.
Fixes #1194

types: use proper jquery event.

---

src/routers/manhattan.mjs

A* used for manhattan router is awesome not because it's bullet proof, but because it has a couple of entry points where we can adjust its behavior. This PR targets one of those places, which is the order of an array used for scanning for the next step. As pathfinding might yield a couple of equally short routes, the results might not be what we expect. We can nudge A* to be a tad bit more predictable if we tell it to search directions based on axis instead of an array of clockwise ordered vectors. It might be a good idea to give the user an arg. to control whether it's horizontal or vertical first, but that's a topic for a different PR.
Before:
After:

fix(routers): fix manhattan scan directions order

---

src/dia/ports.mjs
test/jointjs/elementPorts.js

I've added the possibility to insert ports at specific indexes. This is important if we want to allow dynamic port additions to be possible while having a logically sorted list of ports.
Hope you guys like it!

Support inserting port at position

---

docs/src/joint/api/elementTools/Remove.html

The element tool will pass a link view to the remove action, right?

elementTools.Remove: fix example in documentation

---

src/dia/Paper.mjs
test/jointjs/dia/Paper.js

The `fitToContent()`method didn't work correctly when the content's bottom-right corner had a negative coordinate (either `x`, `y` or both).
```js
paper.scale(1);
const area = paper.fitToContent({
contentArea: { x: -300, y: -300, width: 200, height: 200 }, // bottom-right is x=-100 and y=-100
padding: 0,
allowNewOrigin: 'any'
});
// Assert: `area` is { x: -300, y: -300, width: 200, height: 200 }
```
Also, in edge-case situations the resulting size might not had fall into the given grid but `{ x: 0, y: 0, width: 1, height: 1}` was always returned.
Missing tests for the most of the cases were added.

dia.Paper: fix fitToContent() when the content has negative coordinates

---

src/util/util.mjs
test/jointjs/core/util.js

Fixing https://github.com/clientIO/joint/issues/1460.
```js
// Make sure the resulting string does not contain `undefined` when the last word has a hyphen
joint.util.breakText('word1-word1', { width });
joint.util.breakText('word1 word2-word2', { width });
joint.util.breakText('word1 word2 word3-word3', { width });
```

util.breakText: fix wrapping when the last word contains a hyphen

---

types/geometry.d.ts

Fix incorrect `Polyline` constructor type defintion.
```js
// Use of g.PlainPoints[] is now supported
const p1 = new g.Polyline([{ x: 1, y: 1}, { x: 2, y: 2 }]);
// Use g.Points[] remains supported
const p2 = new g.Polyline([new g.Point(1, 1), new g.Point(2, 2)]);
```

Geometry: fix TS polyline constructor

---

types/joint.d.ts

Add missing `<string>joint.version;` definition.

Typescript: add jointjs version

---

docs/src/joint/api/dia/Graph/prototype/getCells.html
docs/src/joint/api/dia/Graph/prototype/getElements.html
docs/src/joint/api/dia/Graph/prototype/getLinks.html
src/dia/Graph.mjs
test/jointjs/graph.js

- Fixes an issue with embedding mode, which relies on `getElements()` returning the elements in the graph collection order (the elements being sorted by their `z`). The current solution returned the elements (links) in unspecified order (based on object properties order).
- Improve performance for typical graphs where number of elements is similar to number of links (https://jsfiddle.net/kumilingus/L48xyr1f/)

dia.Graph: fix order of cells in getElements() and getLinks()

---

src/g/curve.mjs
src/g/ellipse.mjs
src/g/geometry.helpers.mjs
src/g/line.bearing.mjs
src/g/line.mjs
src/g/point.mjs
src/g/polyline.mjs
src/g/rect.mjs

Use destructuring assignment for a more concise and readable shorthand declaration.

Geometry: declare Math fns shorthands using destructuring

---

docs/src/joint/api/dia/Paper/prototype/options/validateUnembedding.html
src/dia/ElementView.mjs
src/dia/Paper.mjs
test/jointjs/embedding.js
types/joint.d.ts

Add missing validation callback for `embeddingMode` to check if an element can become a new root (to be un-embedded from a parent and become an element without parent).
If invalid -> the position and parent-child relationship is reverted to the state before user interaction.
Rappid Stencil (or an element palette) should take this option into account when an element is dropped from the stencil and the `embeddingMode` is on.

 dia.Paper: add validateUnembedding() option

---

docs/src/joint/api/dia/Paper/prototype/options/anchorNamespace.html
docs/src/joint/api/dia/Paper/prototype/options/connectionPointNamespace.html
docs/src/joint/api/dia/Paper/prototype/options/connectorNamespace.html
docs/src/joint/api/dia/Paper/prototype/options/highlighterNamespace.html
docs/src/joint/api/dia/Paper/prototype/options/linkAnchorNamespace.html
docs/src/joint/api/dia/Paper/prototype/options/routerNamespace.html
src/dia/LinkView.mjs
src/dia/Paper.mjs
types/joint.d.ts

- allow custom routers and connectors to be defined in ESM
- document missing namespace options (`anchorNamespace`, `connectionPointNamespace`, `linkAnchorNamespace`, `highlighterNamespace`)

dia.Paper: add routerNamespace and connectorNamespace options

---

src/dia/ElementView.mjs
test/jointjs/embedding.js

Make sure that the `position` of the descendant elements and the `z` attributes of the connected links are reverted to the state before dragging when `validateUnembedding()` return `false`.

dia.Paper: validateUnemedding() option reverts z-indices and child positions

---

docs/src/joint/api/routers/manhattan.html
src/routers/manhattan.mjs
test/jointjs/routers.js
types/joint.d.ts

As per https://github.com/clientIO/joint/issues/1412 discussion.
```js
const obstacleMap = createObstacleMap(); // any implementation of the obstacle map
const paper = new dia.Paper({
/* ... */
defaultRouter: (vertices, opt, linkView) => {
const isPointObstacle = (point) => obstacleMap.isPointObstacle(point);
return routers.manhattan(vertices, { ...opt, isPointObstacle }, linkView);
}
});
```

routers.Manhattan: add isPointObstacle option

---

types/joint.d.ts

Allow other `mvc.View` [options](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/backbone/index.d.ts#L534-L544) to be used in `dia.HighighterView`.

dia.HighlighterView: fix options TS def

---

src/dia/CellView.mjs
src/dia/Paper.mjs

`dia.CellView`'s `presentationAttributes` and `initFlag` properties can be extended in ES6 syntax now.
```js
class MyView extends ElementView {
initFlag() { return []; }
}
```

dia.CellView: use util.result for presentationAttributes and initFlag

---

src/dia/Cell.mjs
test/jointjs/cell.js

Unnecessary `attrs` were present in the JSON export when `defaults()` defined as a method.
```js
var El = joint.dia.Element.extend({
defaults: function() {
return {
attrs: { test1: { prop1: true }}
};
}
});
var el = new El({
id: 'el1',
attrs: { test1: { prop1: true }, test2: { prop2: true }}
});
assert.deepEqual(el.toJSON(), {
id: 'el1',
attrs: { test2: { prop2: true /* test1 would be redundant */ }}
});
```

dia.Cell: fix toJSON() when defaults() is defined as a method

---

types/geometry.d.ts
types/joint.d.ts
types/vectorizer.d.ts

Fix various issues one would face when inheriting `cellView` classes in Typescript.
```ts
class MyView extends dia.ElementView {
presentationAttributes() {
return { /* */ }
}
render() {
/* ... */
this.updateTransformation();
}
}
```

dia.CellView: update typings for ES6 class extension

---

src/util/util.mjs
test/jointjs/core/util.js

```js
const a = {};
const b = {};
util.setByPath(a, [['__proto__'], 'polluted'], true);
// Assert: b.polluted !== true
```

util.setByPath() - prevent prototype pollution

---

types/joint.d.ts

- ~~use `typeof this` as an instance of the same object (based on https://www.gitmemory.com/issue/microsoft/TypeScript/39902/856601904)~~
- return correct type based on `deep` option (either the clone of this cell, or an array of arbitrary cells)
- fixes #1437

dia.Cell: improve the return type of clone()

---

src/dia/Cell.mjs
test/jointjs/cell.js

From version 1.4 Backbone [added a preinitialize() method to allow for true instance properties and ES6 classes](https://github.com/jashkenas/backbone/pull/3827). Since JointJS overrides `dia.Cell` constructor, this PR makes sure the lifecycle method is called.

dia.Cell: support preinitilize() lifecycle method

---

docs/src/joint/api/dia/Element/prototype/prop.html
docs/src/joint/api/dia/Link/prototype/prop.html
src/dia/Paper.mjs
test/jointjs/dia/Paper.js
types/joint.d.ts

```js
// to improve the update performance instruct the paper to update only the element
// and not the connected links
element.attr(['body', 'fill'], 'red', { isolate: true });
```

dia.Paper: skip update of connected links when isolate flag used

---

types/joint.d.ts

Allow the port position to be defined as a function. 
```ts
(ports: Port[], bbox: g.Rect) => dia.Point[];
```

dia.Element: fix port position TS def

---

demo/erd/src/erd.js
demo/logic/src/logic.js
test/geometry/path.js
test/jointjs/links.js
test/jointjs/paper.js

There are small typos in:
- demo/erd/src/erd.js
- demo/logic/src/logic.js
- test/geometry/path.js
- test/jointjs/links.js
- test/jointjs/paper.js
Fixes:
- Should read `update` rather than `udate`.
- Should read `layers` rather than `alyers`.
- Should read `skipping` rather than `skiping`.
- Should read `lowercase` rather than `lowecase`.
- Should read `highlighting` rather than `highligthing`.
- Should read `diagram` rather than `diagramm`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

src/dia/Paper.mjs
test/jointjs/dia/Paper.js

Make sure that the `stats.priority` always points to the highest priority of all updates done between `beforeRender` and `afterRender`.
```js
// Assert: paper.hasScheduledUpdates() === true
paper.requestViewUpdate(view1, flags1, priority1);
paper.requestViewUpdate(view2, flags2, priority2);
paper.unfreeze({
afterRender: stats => {
// Note: The highest priority is the lowest number.
// Assert: stats.priority === Math.min(priority1, priority2);
}
});
```

dia.Paper: fix update priority stats

---

docs/src/joint/api/dia/attributes/intro.html
src/dia/attributes/calc.mjs
test/jointjs/dia/attributes.js

Add `x` and `y` properties to `calc()` in order to support this use case
```js
element.attr('myTextBackground', {
ref: 'myText',
refX: -5,
refY: -5,
width: 'calc(w + 10)',
height: 'calc(h + 10)',
});
```
without a need of using `refX` and `refY` attributes.
```js
element.attr('myTextBackground', {
ref: 'myText',
x: 'calc(x - 5)',
y: 'calc(y - 5)',
width: 'calc(w + 10)',
height: 'calc(h + 10)',
});
```

dia.attributes: add x and y properties to calc() expression

---

docs/src/geometry/api/g/Rect/prototype/rotateAroundCenter.html
docs/src/joint/api/dia/Element/prototype/getBBox.html
src/dia/Element.mjs
src/dia/Graph.mjs
src/g/rect.mjs
test/geometry/rect.js
test/jointjs/graph.js
test/ts/index.test.ts
types/geometry.d.ts
types/joint.d.ts

Fixes the issue when the user tries embedding an element into another element with non-zero angle.
- **dia.Graph** - `findModelsInArea()`, `findModelsUnderElement()`, `findModelFromPoint()` take the element's rotation into account
- **dia.Element** - add `rotate` option for `getBBox()` (to return the bounding box of the rotated element's model)
- **Geometry** - add `Rect.prototype.rotateAroundCenter()` method (in-place alternative for`Rect.prototype.bbox(angle)`)

dia.Paper: fix embedding mode with rotated elements

---

tutorials/custom-elements.html
tutorials/custom-links.html
tutorials/element-tools.html
tutorials/events.html
tutorials/js/custom-elements.js
tutorials/js/custom-links.js
tutorials/js/events-event-attribute.js
tutorials/js/hyperlinks.js
tutorials/js/link-labels-styling.js
tutorials/js/link-snapping.js
tutorials/js/mark-available.js
tutorials/js/ports-create.js
tutorials/js/ports-link.js
tutorials/js/ports-restrict.js
tutorials/link-labels.html
tutorials/link-tools.html
tutorials/ports.html
tutorials/serialization.html
tutorials/special-attributes.html
tutorials/ts-shape.html

- add `calc()` to `custom element` and `custom link` tutorials
- add `calc()` to `events`, `link labels` and `Typescript` tutorials
- adapt opening sentence of INT articles so they easier to read at first sight

tutorials: add calc() to tutorials  

---

docs/src/joint/api/dia/Paper/prototype/fitToContent.html
docs/src/joint/api/dia/Paper/prototype/getFitToContentArea.html
docs/src/joint/api/dia/Paper/prototype/getFitToContentBBox.html
src/dia/Paper.mjs
test/jointjs/paper.js
types/joint.d.ts

- split `fitToContent()` into a new `getFitToContentArea()` method (to get the resulting paper bounding box to be used for further calculations).
- prevent `translate` event being triggered after `setOrigin()` without actual change of origin
- prevent `resize` event being triggered after `setDimension()` without actual change of size

dia.Paper: refactor `fitToContent()`

---

src/dia/Paper.mjs

Fixes https://groups.google.com/g/jointjs/c/sBUrHJ65YFo/m/V73hPOWTAwAJ.

dia.Paper: make sure `paper:mouseleave` event is always triggered

---

demo/container/src/index.js
docs/demo/layout/DirectedGraph/js/clusters.js
docs/src/joint/api/dia/Element/prototype/embed.html
docs/src/joint/api/dia/Element/prototype/unembed.html
src/dia/Cell.mjs
test/jointjs/basic.js
types/joint.d.ts

Fixes #179.
`embed()` and `unembed()` accepts either a single cell or an array of cells.

dia.Cell: embed() and umbed() to accept an array of cells

---

src/dia/Paper.mjs
test/jointjs/dia/Paper.js

when the graph contains link to link connection and is in the sync mode

dia.Paper: fix `graph.clear()` causing an infinite loop

---

src/dia/attributes/index.mjs

When `href` or `xlink:href` in use:
```js
const image = new standard.BorderedImage({ attrs: { image: { href: 'my-image.png' }}});
// Should this trigger a new network request?
image.addTo(graph); // YES
image.attr('image/href', 'my-other-image.png'); // YES
image.attr('image/href', 'my-other-image.png'); // NO
image.attr('border/stroke', 'red'); // NO
image.resize(100, 100); // NO
```

dia.attributes: prevent redundant network requests when href in use

---

src/dia/Cell.mjs
test/jointjs/basic.js
types/joint.d.ts

- fixes the order of transition events (1. `transition:start`, 2. `transition:end`).
- fixes the arguments of `transition:end` event handler
- maintain the  backwards compatibility from `v3.4` (schedule multiple transitions of the same property at once) while keeping the ability to stop the delayed events (feature of `v3.5`).

dia.Cell: fix transition events order

---

package-lock.json
package.json
src/dia/Cell.mjs
test/jointjs/cell.js

Requires Backbone [changes](https://github.com/jashkenas/backbone/commit/0b1c2e3fce3156fcb9819b8bbf8885456e4e1055) to be released.
Add support for custom `idAttribute`.
```ts
const MyCell = joint.dia.Cell.extend({ idAttribute: 'myId' });
const cell = new MyCell({ myId: '123'});
cell.addTo(graph);
// Assert:
graph.getCell('123') === cell
```

dia.Cell: support custom idAttribute

---

docs/js/api.js

- JointJS docs should show all items again after deleting query with keyboard
- open V items when you visit page, just to make behaviour consistent with geometry items behaviour

docs: fix search on delete query

---

src/V/index.mjs
test/vectorizer/vectorizer.js

The PR allows empty lines to be annotated.
The actual `line-height` of an empty line is calculated based on the annotations now.
Note that the empty line at the beginning of the text is annotated at `(-1,0>`.

Vectorizer: text() reads empty line heights from annotations

---

docs/src/joint/api/connectors/curve/intro.html
src/connectors/curve.mjs
test/jointjs/connectors.js

Add `rotate` option to `connector.Curve`.
```js
el.set('angle', 45);
el.set('connector', {
name: 'curve',
args: {
rotate: true // take the element's angle into account
}
});
```

connectors.Curve: rotate option

---

src/dia/attributes/index.mjs
test/jointjs/dia/attributes.js

The dimension attributes (`width`, `height`, `r`, `rx`, `ry`) must be always greater than or equal to `0`. The browser throws `"A negative value is not valid"` otherwise.
This PR ensures that the result of the `calc()` expression for the listed attributes is valid.

attributes: prevent negative values for dimension attributes

---

docs/src/joint/api/elementTools/Button.html
src/linkTools/index.mjs
test/jointjs/dia/elementTools.js

A convenient way to place buttons on the elements.
```js
new elementTools.Remove({
// the button will be at the bottom-right corner
// and 10 pixels towards the center of the element
x: 'calc(w - 10)',
y: 'calc(h - 10)'
});
```

elementTools.Button: enable calc() expression for x and y

---

docs/src/joint/api/dia/attributes/textWrap.html
src/dia/attributes/index.mjs
test/jointjs/dia/attributes.js
types/joint.d.ts

- Use `calc` expression in `textWrap` for more flexible bounding box definition
```js
// leave 5 pixels margin around the text
{ textWrap: { width: 'calc(w - 10)', height: 'calc(h - 10)' }}
```
- Use `null`  in `textWrap` to prevent wrapping in a given dimension 
```js
// no limit to the text height
{ textWrap: { width: 'calc(w)', height: null }}
```
- fix `textWrap` tests (add an option to  control what `breakText` method is used in `textWrap`)
- update the documentation
- deprecate `text` attribute inside `textWrap` (in favor of the top-level `text` attribute).

attributes.textWrap: enable calc() expression for width and height

---

docs/src/joint/api/layout/Port.md
src/layout/ports/port.mjs
test/jointjs/elementPorts.js
types/joint.d.ts

- feat: use `calc()` expressions to position individual ports (for `x` and `y` attributes)
- fix: take `angle` into account when defined on a port
- fix: update Typescript definition for Port layouts
```js
const rectangle = new shapes.standard.Rectangle({
ports: {
groups: {
myGroup: {
position: 'absolute',
markup: [{
tagName: 'rect',
attributes: {
'x': -10,
'y': -10,
'width': 20,
'height': 20,
'stroke-width': 2,
'fill': '#FFFFFF',
'stroke': '#000000'
}
}],
}
},
items: [{
group: 'myGroup',
args: {
x: 'calc(w+10)', // NEW
y: 10,
angle: 45 // FIXED
}
}, {
group: 'myGroup',
args: {
x: 'calc(w+10)', // NEW
y: 'calc(h-10)', // NEW
}
}]
}
});
```

layout.Port: enable calc() expressions

---

docs/src/joint/api/dia/attributes/intro.html
src/dia/attributes/calc.mjs
test/jointjs/dia/attributes.js

Make `calc()` expression understand division to increase the comfort and precision.
```js
// precision
calc(0.3333 * w)
// vs.
calc(w / 3)
// comfort
calc(0.5 * w)
// vs.
calc(w / 2)
```

dia.attributes: calc() expression supports division

---

src/linkTools/index.mjs

Currently, the link tool throws an exception when the user touches the button. This PR fixes the issue.

linkTools.Connect: fix touch support

---

types/geometry.d.ts

Changed return type to match [docs](https://resources.jointjs.com/docs/jointjs/v3.5/geometry.html#g.Curve.prototype.getSkeletonPoints).

g.Curve: getSkeletonPoints return type

---

types/joint.d.ts

Before these changes this didn't had the correct types, it just had `any`:
```ts
paper.on({
'link:mouseenter': (linkView) => {
},
})
```
With this changes `linkView` correctly has the `joint.dia.LinkView`

types: fix on event handler types when passed an events object

---

docs/src/joint/api/util/breakText.html
src/dia/attributes/index.mjs
src/util/util.mjs
test/jointjs/core/util.js
types/joint.d.ts

Add option to preserve the text spaces (avoid all consecutive spaces to be deleted and replaced by one space, and preserve a space at the beginning and the end of the text) while text wrapping.

util.breakText: add preserveSpaces options

---

types/joint.d.ts

Fixes
```ts
const cell = new dia.Cell<{foo: string, bar: string}>({foo: 'foo', bar: 'bar'})
cell.prop({foo: 'foo2'}) // this would fail because it was asking for the bar property
```

types: fix cell.prop object types

---

types/joint.d.ts

dia.Link currently allows this but shapes.standard.Link does not:
```ts
interface Attributes {
foo: string;
}
class CustomLink extends dia.Link<Attributes> {} // dia.Link is generic
class CustomLink2 extends shapes.standard.Link<Attributes> {} // this is not possible with current types
const link = new CustomLink({
// nice autocomplete here in the editor for `foo` variable
foo: "foo",
});
const link2 = new CustomLink2({
// no auto completion and no warnings that a number was passed instead of a string
foo: 3,
});
```

types: allow passing generic attributes to links under shapes.standard

---

docs/src/joint/api/elementTools/Button.html
docs/src/joint/api/elementTools/Control.html
docs/src/joint/api/elementTools/Remove.html
docs/src/joint/api/linkTools/Button.html
docs/src/joint/api/linkTools/Remove.html
docs/src/joint/api/linkTools/Segments.html
docs/src/joint/api/linkTools/SourceAnchor.html
docs/src/joint/api/linkTools/SourceArrowhead.html
docs/src/joint/api/linkTools/TargetAnchor.html
docs/src/joint/api/linkTools/TargetArrowhead.html
docs/src/joint/api/linkTools/Vertices.html
src/elementTools/Control.mjs
src/linkTools/Anchor.mjs
src/linkTools/Arrowhead.mjs
src/linkTools/Button.mjs
src/linkTools/Segments.mjs
src/linkTools/Vertices.mjs
types/joint.d.ts

Add an option to easily change the size of the tools.
```js
// enlarge the tools 2x
const tools1 = new dia.ToolsView({
tools: [
new linkTools.TargetArrowhead({ scale: 2 }),
new linkTools.SourceArrowhead({ scale: 2 }),
new linkTools.Vertices({ scale: 2 }),
new linkTools.Segments({ scale: 2 }),
new linkTools.SourceAnchor({ scale: 2 }),
new linkTools.TargetAnchor({ scale: 2 })
]
});
// shrink the tools to half their original size
const tools2 = new dia.ToolsView({
tools: [
new elementTools.Control({ scale: 0.5 }),
new elementTools.Button({ scale: 0.5 }),
new elementTools.Connect({ scale: 0.5 })
]
});
```

linkTools, elementTools: add scale option

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

- Add Issue template for bugs. Template will render as form for the user as shown in the picture below (Tested on personal repo).
- label `bug` will automatically be added to issue
- `title`, `what happened?`, and `version` are required
- `browser` and `os` are optional
- Add link to github discussions at beginning to make sure people create a discussion for general question
After clicking on new issue, the following will be displayed:
- `config.yml` contains `blank_issues_enabled` as false. That means users cannot create a blank issue anymore in this section. They have to create a bug report or discussion.
- The `SECURITY.md` policy will be displayed here too to show the user how to report a problem
- Add link to github discussions in this section
Blog describing process on github: …

chore: add github issue template

---

docs/src/joint/api/dia/Element/prototype/prop.html
docs/src/joint/api/dia/Link/prototype/prop.html
tutorials/custom-attributes.html

- add `change` event to `Link` and `Element` prop methods
- fix code snippet spacing in `custom attributes` tutorial
- update `custom attributes` tutorial with `change` event example line:[246]
docs:
custom attributes:

docs: update dia.Element.prototype.prop with change event

---

src/dia/CellView.mjs
src/highlighters/mask.mjs
src/highlighters/stroke.mjs
test/jointjs/elementView.js
types/joint.d.ts

The `rotation` matrix is not applied on elements outside the `rotatable` group (if present) when calculating the bounding box.
The `rotation` matrix is applied on the highlighter node when inside the `rotatable` group.
The highlighters (`stroke`, `mask`) does not render properly on elements with `rotatable` group.
Before:
After:

dia.ElementView: fix getNodeMatrix() and getNodeBBox() for elements wth rotatable group

---

types/joint.d.ts

Revert "types: allow passing generic attributes to links under shapes.standard"

---

.github/workflows/stale.yml

- fix typo in exempt tag for `technical debt`

chore: fix github stale action typo

---

docs/src/joint/api/dia/Paper/events.html
src/dia/Paper.mjs
src/util/util.mjs
types/joint.d.ts

As discussed previously via email, this is an initial draft for the support of 2-axis-scroll and pinch-to-zoom (touchpad devices). There are some things that we must clear out before merging this!
The patch implements 2-axis-scroll, which is something very common when using touchpad devices (and greatly improves the UX!). It also implements pìnch-to-zoom gestures.
Initially, we discussed to start only with the 2-axis-scroll patch, but since the pinch-to-zoom is a +2 lines net addition on top of the 2-axis-scroll patch and since it would actually cost more to split it rather than keep it, I decided to just push them both in the same PR. If you still feel that we should drop the pinch-to-zoom patch, removing it should be easy.
This patch could be used like this:
```
"TBD_system:scale": …
```

[WIP] 2-axis-scroll / pinch-to-zoom support

---

src/dia/CellView.mjs

Passing cellView instance as the last argument when calling - set. qualify, position and offset methods
Typescript - Issue
Unable to access the current instance of the cellView inside the "static" variable.
The change is based on [discussion](https://github.com/clientIO/joint/discussions/1771)

CellView - Passing cellView instance as the last argument when calling - set, qualify, position and offset methods

---

src/dia/HighlighterView.mjs
src/highlighters/mask.mjs
src/highlighters/stroke.mjs
test/jointjs/dia/HighlighterView.js
types/joint.d.ts

Fix `stroke` and `mask` highlighter angle and position for rotated elements. Add test cases for many element configurations (angle, rotatable group, highlighter layer).
This [PR](https://github.com/clientIO/joint/pull/1791) made highlighters not to work properly for rotated elements without rotatable group.

dia.HighlighterView: fix stroke and mask highlighter size and position

---

types/geometry.d.ts
types/joint.d.ts

- Add missing protected method type for `findPath` in `dia.LinkView`
- Add missing parameter for `parallel` method in `g.Line`
Both of these errors were encountered in `VSMElectronicInformationFlowView`.

dia.LinkView, g.Line: update types

---

src/dia/Cell.mjs
test/jointjs/basic.js

Should use `assign` instead of `defaults`, otherwise `cell.isEmbeddedIn(parent, { deep: false })` cannot set opt.deep to false.

fix isEmbeddedIn opt

---

src/util/svgTagTemplate.mjs
test/jointjs/core/util.js
types/joint.d.ts

Add support for embedded expressions (string interpolation) when using `util.svg` as tagged template.
```js
const color = 'red';
const markup = util.svg`<rect @selector="body" fill="${color}"/>`
```

util.svg: support embedded expressions

---

src/util/svgTagTemplate.mjs
test/jointjs/core/util.js

Prevent string `"null"` for `className` if not provided.
```js
const markup = util.svg`<rect/>`;
// Assert: markup[0].className !== null;
```

util.svg: prevent null className

---

.travis.yml

Temporarily downgrade the nodeJS version in TravisCI.
Node 18 (LTS) is not compatible with the current ubuntu version used in TravisCI
- https://github.com/nodejs/node/issues/42351#issuecomment-1068424442
- https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/4

chore: update travis nodejs version

---

src/linkTools/Segments.mjs

Make sure all links stay orthogonal while dragging a handle.
In some cases, links could become non-orthogonal when using linkTools.Segments tool.

fix(linkTools.Segments): non-orthogonal edge cases

---

src/V/index.mjs
test/vectorizer/vectorizer.js

Properly handle multiple tokens in `removeClass()` and `toggleClass()` prototype methods.
```js
const g = V('g');
g.addClass('token1 token2'); // worked already
g.removeClass('token1 token2'); // fixed
g.toggleClass('token1 token2'); // fixed
```
See issue: https://github.com/clientIO/joint/issues/1900

fix(Vectorizer): fix removing & toggling multiple classes at once

---

src/V/index.mjs
src/g/points.mjs
test/geometry/polyline.js

Fix RegEx in code to avoid potential ReDoS attacks.
JavaScript's RegEx engine uses backtracking which means that its worst-case time complexity can be polynomial or even exponential. This can happen when the regex fails to find any matches in the queried string, when the regex is written in such a way that forces the engine to investigate each character in the queried string multiple times.
The polynomial worst-case complexity happens in cases such as `/\w+\(/`. Here, the intention is to find a string of letters terminated with a `(`. If the queried string does end with a `(`, all is good. However, if the queried string doesn't end with a `(`, the engine needs to do a lot of backtracking, which leads to a potential ReDoS vector.
The engine needs to do a pattern that looks like this: start …

Fix RegEx queries in code

---

css/layout.css

Fixes Issue #1926
There is a CSS rule in `rappid.css` (actual source: `joint/css/layout.css`) which is missing a vendor prefix:
```diff
.joint-element * {
+  -webkit-user-drag: none;
user-drag: none;
}
```
This is the only rule that is missing it; all other places where `user-drag` is used have the vendor prefix.

fix(css): layout.css prefixed user-drag property

---

src/dia/Paper.mjs
test/jointjs/paper.js

Fix of the `element:magnet:contextmenu` event handling in dia.Paper. Preserve events hierarchy so it is possible to use `stopPropagation()` in `element:magnet:contextmenu` handler to prevent triggering of the `element:contextmenu` and `cell:contextmenu` events.

dia.Paper: fix magnet contextmenu handling

---

types/joint.d.ts

Add missing `dia.Link.defaultLabel` property to TS which uses the existing `Link.Label` interface.
Also remove `dia.Link.labelProps` which seems to have been a bug.
Additionally, mark `dia.Link.labelMarkup` as deprecated, in alignment with a comment in our code coming from the same time.

fix(dia.Link): add defaultLabel to TS

---

src/linkTools/Anchor.mjs
test/jointjs/dia/linkTools.js

The `linkTools.Anchor` visual aid for displaying the available anchor position was incorrectly calculated for links (the current paper transformations were applied on the area bounding box twice).
The PR also makes sure that the `Anchor` tool fails silently if the `area` markup is not provided.

fix(linkTools.Anchor): incorrect area bounding box for link-link connections

---

css/layout.css

Remove the unprefixed `user-drag` property from `joint/css/layout.css`, since it is not supported by any browsers and some tests are throwing errors.
Note: The prefixed version was recently introduced in #1933.
```diff
.joint-element * {
-webkit-user-drag: none;
- user-drag: none;
}
```

fix(css): layout.css remove unprefixed user-drag property

---

docs/src/joint/api/dia/Graph/prototype/addCell.html

Fixes #1867
- add missing `opt` parameter and descripstions in `addCell`

fix(docs): add missing options parameter in addCell

---

src/dia/Cell.mjs
test/jointjs/cell.js

As per issue #1939 
`propertyPathArray` and `propertyValue` must be available no matter what signature was used to call `prop()` (or `attr()`).
```js
cell.on('change', (cell, { propertyPath, propertyPathArray, propertyValue, rewrite }) => {
console.log('propertyPath', propertyPath); // do not use this
console.log('propertyPathArray', propertyPathArray);
console.log('propertyValue', propertyValue);
console.log('rewrite', rewrite);
if (!rewrite) {
let attributes;
if (propertyPathArray.length > 0) {
attributes = joint.util.setByPath({}, propertyPathArray, propertyValue);
} else {
attributes = propertyValue;
}
const propertiesPaths = joint.util.flattenObject(attributes, '/');
console.log(propertiesPaths);
} else {
// TBI (using cell.previous('attrs'))
}
});
cell.attr('line', { stroke: 'red' …
```

fix(dia.Cell): always send propertyPath and propertyValue options when calling prop()

---

src/dia/Cell.mjs
test/jointjs/cell.js

Unify the `prop()` method mergin behavior. Do not **rewrite** the current values unless the the `{ rewrite: true }` option was passed.
`dia.Cell` `prop()` method does not merge existing properties with the new ones in case when the path is a top level attribute and the value is an object. It preserves the current values in all other cases.
```js
// Removes `b`
cell.prop('a', { b: 1 });
cell.prop('a', { c: 2 });
cell.prop('a') ~== {  c: 2 } // INCORRECT
```
```js
// Preserves `b`
cell.prop('a/b', '1');
cell.prop('a/c', '2');
cell.prop('a') ~== { b: 1, c: 2 }
```
```js
// Preserves `b`
cell.prop({ a: { b: 1 }});
cell.prop({ a: { c: 2 }});
cell.prop('a') ~== { b: 1, c: 2 }
```
```js
// Preserves`b`
cell.prop('a', { b: 1 });
cell.prop('a', { c: 2 });
cell.prop('a') ~== { b: 1, c: 2 }
``` …

fix(dia.Cell): inconsistent merging behavior in prop()

---

docs/src/joint/api/dia/Paper/prototype/requireView.html
src/dia/Paper.mjs
test/jointjs/dia/Paper.js

If a view is updated manually (by calling `requireView`), the `beforeRender` and `afterRender` callbacks, and `render:done` event must be triggered.
It is important to always let the outside world know that the CellView has been changed. Right now, the updates can happen without any notification, when there is a scheduled update for the view and `requireView` is called.
An example where this can cause a problem is when the `linkPinnings` parameter is set to `false` and the link is rolled back (removed) at the end of the interaction if it is not connected to another cell. In this case, the link is deleted, the `checkMouseleave` function is called, and the udpates to the view are [executed synchronously](https://github.com/clientIO/joint/blob/master/src/dia/CellView.mjs#L1169) without any …

fix(dia.Paper): requireView() must trigger before & after render

---

docs/templates/api.html

- add missing lang attribute to `docs` template in order to improve SEO performance 
Error was listed by SERanking service.

chore(seo): add missing lang attr to docs template

---

src/util/util.mjs
test/jointjs/core/util.js

feat: return test
Allow usage of pixel units when breaking text with `util.breakText` function. Pixels are a default unit when no unit is provided.
```js
const styles = {
fontSize: 14,
fontFamily: 'Arial, helvetica, sans-serif'
};
const t = 'This is very very very very very very very very very very very very very very very very very very very very very very long text';
// valid
const lineHeight = 20;
// valid as well
// const lineHeight = '20px';
const cell = new joint.shapes.standard.Rectangle({
size: { width: 50, height: 250 },
attrs: {
text: {
text: t,
textWrap: {},
...styles,
lineHeight
}
}
});
graph.addCell(cell);
```
fixes: *util.breakText - incorrect result when custom `lineHeight` provided*
Easier and cleaner usage of `util.breakText` function. Allow usage of pixels.

feat(util.breakText): support lineHeight in px

---

docs/src/joint/api/dia/Paper/prototype/fitToContent.html

A link in `dia.Paper.prototype.fitToContent` documentation does not work because it is pointing to a non-existent signature (`dia.Paper.protoype.getFitToContentBBox`).
The correct target is `dia.Paper.prototype.getFitToContentArea`.

docs(dia.Paper): Replace dead link to getFitToContentArea function

---

.csslintrc

The CSS lint config was used with `grunt-contrib-css`. 
https://www.npmjs.com/package/grunt-contrib-csslint
We don't use this dependency anymore, so the config is redundant. The dependency was removed in this old PR:
https://github.com/clientIO/joint/pull/1012

chore: remove unused css lint config

---

tutorials/ports.html

- update `Working with ports` tutorial with `portProp` example

docs(tutorials): add portProp example to ports tutorial

---

src/dia/LinkView.mjs
test/jointjs/links.js

When dragging a link label, the label should remember the coordinates of the initial cursor position.
The current behavior is that when dragging starts, the label snaps such that its anchor is under the cursor. This PR prevents that by saving the initial offsets of cursor coordinates from label anchor coordinates - and applying them to the cursor coordinates while dragging is underway.
The label anchor (center of the label by default) is still the reference point for label position (e.g. `distance` property). The offset is purely visual.

fix(dia.LinkView): remember initial cursor offset from label anchor when dragging

---

src/dia/Paper.mjs

Trigger `blank:mousewheel` and `cell:mousewheel` events when *CTRL* key pressed but there are no `paper:pinch` subscribers.
The `blank:mousewheel` and `cell:mousewheel` events are no longer triggered if no event attached to the `paper:pinch` and `CTRL` keys is pressed. This may have broken an application that depended on these events prior to `v3.6`, when the `pinch` event was introduced.

fix(dia.Paper): trigger mousewheel event when CTRL key pressed but there are no paper:pinch subscribers

---

src/dia/LinkView.mjs
test/jointjs/links.js

Labels using `keepGradient` and `absoluteOffset` have unexpected rotation applied to them.
The issue was caused by the `g.Point.offset()` method being applied on `start` point of `tangent` line. The method modifies the point in-place.
This caused the `tangent.start` point stay in this modified state beyond the intended scope (i.e. out-of-sync with `tangent.end`) - during the time of the `angle` calculation, which happens afterward. On top of the `tangent` angle, the `angle` was thus then also incorrectly adding the angle between the modified `tangent.start` position and the original `tangent.end` position.
This PR fixes the issue by cloning the `tangent.start` point and applying the offset method to the clone. This also applies to the fallback algorithm, which uses `path.start` in absence …

fix(dia.LinkView): fix incorrect absolute offset label rotation

---

src/g/curve.mjs
test/geometry/curve.js

In the Links demo, dragging the labels on link7 ("First", "Second") exposes an issue where relatively-positioned labels are jumping back and forth under the cursor (and unexpectedly snapping to various points along the link).
This is not the issue on link6 ("Label").
The problem stemmed from the fact that link7 is a straight-line curved path (meanwhile, link6 is actually a straight line).
This was an unhandled edge case in the `dia.LinkView.getConnectionSubdivisions() -> g.Path.getSegmentSubdivisions() -> g.Curve.getSubdivisions()` function, which caused the function to exit early after only 2 iterations. In general, increasing precision by 1 corresponds to an increase of 2 in the average number of iterations needed - in effect, this meant that the subdivision calculation result …

fix(g.Curve): label jumping while being dragged along straight-line curves

---

src/layout/ports/portLabel.mjs

Improvements to the Port Label Layout text positioning.
1.  For `outsideOriented` and `insideOriented` layouts, adjust the `y` coordinate of the port label's `<text/>` to align it properly.
2. For `manual` layout, stop copying all `g.Rect` properties and methods to the layout result. None of the properties should actually be copied 
- `width` and `height` is not used
- `x` and `y` which is the origin of the element (always 0x0) does not make sense here. the `x` and ` y` is an offset from the port
The **Port Label** layout must always align the center of the label with the port.
**Before:**
**After:**

fix(layouts.PortLabel): center the position of oriented outside/inside labels, remove redundant code from manual layout

---

src/highlighters/mask.mjs
test/jointjs/dia/HighlighterView.js

The `<mask/>` element inside paper's `<defs/>` should not copy `class` attributes from the source cell nodes.
If external CSS is used to style elements, this should prevent `mask` nodes inside `defs` from unintentionally becoming the target of CSS rules (in the context of `<mask/>` children nodes, it makes no sense to change their presentation attributes).

fix(highligters.mask): prevent class attribute from being copied over to mask element

---

.gitignore
grunt/config/ts.js
test/ts/index.test.ts
test/ts/tsconfig.json
test/ts/vectorizer.test.ts
types/joint.d.ts

Fixes #2018 
-  Add separate `tsconfig` for `tests`. Now `grunt` just runs `tsc`. All of the TS options are not available in `grunt-ts`.
https://github.com/TypeStrong/grunt-ts/issues/442
-  Add `pretty: true` to `tsconfig` in order to format output nicely
-  Add `extends` to various parameters - needed in order to add a constraint in all instances
-  Fix the following errors with `clone()` via extending parameters 
- add type of `[key: string]: any;` to `mvc.ViewOptions`. This allows the following test to pass in `index.test.ts`. Otherwise `{ attribute: string }` doesn't have properties in common with `ViewOptions`.
```js
class AttributeHighlighterView extends joint.dia.HighlighterView<{ attribute: string; }> {
preinitialize() {
this.UPDATE_ATTRIBUTES = function() { return …
```

types: enable use of strict in tsconfig

---

src/linkTools/Anchor.mjs

Make sure the `cell:mouseleave` event is triggered after drag & drop interaction when the pointer is outside the linkView on `mouseup`.
The problem is that on `mousedown` we undelegate all paper events to prevent other events like `mouseover` and `mouseout` events from triggering during drag & drop interaction, and delegate them back on `mouseup`.
The ideal solution could be not to undelegate the events and use `setPointerCapure` API instead. This PR is just a simple fix of existing problem and it is not addressing this technical debt.

fix(linkTools.Anchor): make sure mouseleave event is triggered after drag&drop interaction

---

docs/css/api.css
docs/demo/shapes/shapes.standard.html

While checking all documentation files for task #1948, I discovered some file paths in the `docs` folder which appear to be wrong.
- `docs/css/api.css`: font path of bold italic PP Fraktion Mono has duplicated `/fonts` string
- changed to `../fonts/PPFraktionMono/PPFraktionMono-BoldItalic.woff` which is in line with other font paths in the file 
- `docs/demo/shapes/shapes.standard.html`: stylesheet path doesn't point to anything (note that we care about what happens inside `build/docs`)
- changed to `../../css/lib/joint.min.css` (like it is in `docs/demo/shapes/shapes.devs.html`)

docs: file path fixes

---

.github/DISCUSSION_TEMPLATE/q-a.yml

Github discussion forms are in public beta as mentioned in the link below, so they should be available soon. They are subject to change, so we will need to review the `.yml` template before merging.
https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms
*"The name must correspond with the slug for one of your discussion categories."*
- File has been named `q-a.yml` as that corresponds to our most popular discussion type

chore(github): add github discussion template

---

test/ts/tsconfig.json
test/ts/vectorizer.test.ts

- enable `strictBindCallApply`. Now all `strict` rules are enabled in config.
- adjust tests in `vectorizer.test.ts` due to issue with overloads in TS.

chore(tsconfig): update strict rules

---

tutorials/elements.html
tutorials/hierarchy.html
tutorials/links-patterns.html
tutorials/multiple-papers.html
tutorials/ports-archive.html
tutorials/testing-e2e-playwright.html

- fix links internal that are broken or don't exist anymore (`v1.0` of docs)
- fix external links(playwright) that have changed

docs(tutorials): fix broken links

---

package.json

- Add `--ext mjs` to linting script as `mjs` is not available by default in the eslint version we currently use.
https://github.com/eslint/eslint/issues/14828

chore(eslint): add mjs extenstion to script

---

demo/shapes/foreign-object.html
demo/shapes/src/foreign-object.js
src/util/svgTagTemplate.mjs
test/jointjs/core/util.js

Make SVG tag template (`util.svg`) to support foreign objects. Addresses 3 problems in resulting JSON markup:
1. **Wrong `tagName` for HTML elements**
```html
<div namespace="http://www.w3.org/1999/xhtml"></div>
```
was parsed incorrectly as:
```json
{ "tagName": "DIV", "namespaceURI": "http://www.w3.org/1999/xhtml" }
```
*Note: XHTML documents must use lower case for all HTML element and attribute names*
After this change:
```json
{ "tagName": "div", "namespaceURI": "http://www.w3.org/1999/xhtml" }
```
2. **`textContent` property contains text nodes from all descendants**
The following markup:
```html
<p>a<span>b</span>c</p>
```
was parsed incorrectly as:
```json
{ "tagName": "p",  "textContent": "abc", "children": [{ "tagName": "span", "textContent": "b" }] }
```
*Note: it will render …

fix(util.svg): support foreignObject

---

.github/DISCUSSION_TEMPLATE/q-a.yml

- fix discussion template. Title cannot be an empty string.

chore(github): fix github discussion template

---

docs/src/joint/api/connectionPoints/boundary.html
src/connectionPoints/index.mjs
test/jointjs/connectionPoints.js
types/joint.d.ts

If the `selector` option of the `boundary` link connection point is set to `false`, the connection point is found on the boundary of the `magnet` regardless of what type of SVGElement it is. Previously, it would try to find the first non-group node descendant of the `magnet` if it the `magnet` was an `SVGGroup`, and this behavior could not be stopped.
See comment: https://github.com/clientIO/joint/discussions/2028#discussioncomment-4901097
Fixes #2030.

fix(connectionPoints.Boundary): disabling automatic magnet lookup via selector option

---

docs/src/joint/api/dia/Cell/markup.html
docs/src/joint/api/util/svg.html
src/util/svgTagTemplate.mjs
src/util/util.mjs
test/jointjs/core/util.js
types/joint.d.ts

This PR adds new functionality to the `svgTagTemplate` util function. Now it is correctly parse several chunks of text nodes, preserving the order and rendering them back as text nodes. For example `<span>a<span>b</span>c</span>` will be rendered exactly the same in the final DOM. Also it uses HTML style space removing, so it will preserve only one space instead of several spaces and/or other special symbol (like a new line).
Also this PR adds a new logic for processing text nodes into the `parseDOMJSON` function in the `util` module. Now this function will parse json with string `children` entries as HTML text nodes.
For example 
```
{
tagName: 'div'
children: [
'a',
{
tagName: 'span',
children: ['b']
},    
'c',
]
}
```
will be parsed as `<div>a<span>b</span>c</div>`.

svgTagTemplate: correct textNode parsing

---

demo/container/src/index.js
demo/container/src/joint.shapes.container.js
demo/sequence/src/joint.shapes.sd.js
docs/css/api.css
docs/src/joint/api/dia/Element/prototype/fitEmbeds.html
docs/src/joint/api/dia/Element/prototype/fitEmbeds.md
docs/src/joint/api/dia/Element/prototype/fitParent.md
docs/src/joint/api/dia/Element/prototype/fitToChildren.md
docs/src/joint/api/shapes/devs.html
src/dia/Element.mjs
src/layout/DirectedGraph/DirectedGraph.mjs
test/jointjs/basic.js
test/jointjs/elements.js
types/joint.d.ts

- Added `dia.Element.fitParent()` method - to adjust bbox of parent/ancestors of this element to envelop element's bbox (including padding, if any).
- Added `dia.Element.fitToChildren()` method as an alias for `dia.Element.fitEmbeds()` - to adjust bbox of this element to envelop bbox of element's children/descendants (including padding, if any).
- Kept `padding` and `deep` options of both methods. 
- Added `expandOnly` and `shrinkOnly` options to both methods - to limit which types of adjustments are allowed.
- If `shrinkOnly` is used and there is no overlap between the parent element and its children, nothing happens.
- Note that when `shrinkOnly` is used together with the `deep` option, each step of the algorithm is independent - always only the bbox of the currently evaluated element …

feat(dia.Element): add fitParent() to fit embedding parent to specified child

---

demo/embedding/front-and-back.html
demo/embedding/front-and-back.js
docs/src/joint/api/dia/Cell/prototype/z.html
src/dia/Cell.mjs
test/jointjs/basic.js
types/joint.d.ts

Fixes mixing up z-indexes of nested cells when `Cell.toFront` or `Cell.toBack` is called.
Having elements like this:
```js
const r1 = new joint.shapes.basic.Rect({});
const r2 = new joint.shapes.basic.Rect({
z: 10
});
const r3 = new joint.shapes.basic.Rect({
z: 5
});
r1.embed(r2);
r1.embed(r3);
```
Calling `r1.toFront({ deep: true })` (in `master`) breaks stacking:
This fix gives an expected result:
-----
There is one drawback of the new solution. When we call `toFront` or `toBack` again and again, the internal condition `shouldUpdate` is always resolved as true and z-indexes are further recalculated, even though the stacking stays correct.
Let me know if you wanted to resolve this recalculation issue as well…

fix(dia.Cell): preserve stacking of nested cells when toFront/toBack is called

---

docs/src/joint/api/dia/Paper/prototype/defineMarker.html
src/dia/Paper.mjs
test/jointjs/dia/attributes.js
types/joint.d.ts

This PR fixes a bug in which target markers do not get rotated by 180 degrees when defined via `marker.markup`.
The expected behavior is that the two ways to define markers (via `marker.type` + attributes as children of `_marker`, and via `marker.markup`) would produce the same results. That is already the case for `sourceMarker` and `vertexMarker` - but `targetMarker` is handled via extra logic which adds a `transform: rotate(180)` attribute to whatever marker definition is provided.
Due to the way markers were previously being processed in the `dia.Paper.defineMarker()` function, that added transformation attribute was not taken into account in the `marker.markup` case. This PR fixes that inconsistency.

fix(dia.Paper): target markers are rotated as expected when using marker.markup

---

demo/paper/index.html
demo/paper/src/paper.js
docs/src/joint/api/dia/Paper/prototype/scaleContentToFit.html
docs/src/joint/api/dia/Paper/prototype/transformToFitContent.html
src/dia/Paper.mjs
test/jointjs/dia/Paper.js
types/joint.d.ts

Added `verticalAlign` and `horizontalAlign` options for `dia.Paper.scaleContentToFit` function.
- opt.verticalAlign – a string which specifies how the content shold be vertically aligned in the transformed paper. The options are `'top'`, `'middle'` and `'bottom'`. By default the `opt.verticalAlign` is `'top'`.
- opt.horizontalAlign – a string which specifies how the content shold be horizontally aligned in the transformed paper. The options are `'left'`, `'middle'` and `'right'`. By default the `>opt.horizontalAlign` is `'left'`.
Also `dia.Paper.scaleContentToFit` is now deprecated in favor of an alias `dia.Paper.transformToFitContent` which shows what is actually happening inside the function. For example the demo [https://www.jointjs.com/demos/paper-attributes](url) shows changes in the …

dia.Paper.scaleContentToFit: adding alignment options

---

src/connectors/curve.mjs
test/ts/index.test.ts
types/joint.d.ts

Fixed types so they match js curve object structure. Also made small fix to the curve function itself (it threw errors on parameters as plain points for sourcePoint and targetPoint)

connectors.curve: types fix

---

demo/roi/css/roi.css
demo/roi/index.html
demo/roi/src/roi.js
demo/shapes/src/foreign-object.js
docs/src/joint/api/dia/CellView/prototype/isDefaultInteractionPrevented.html
docs/src/joint/api/dia/CellView/prototype/preventDefaultInteraction.html
docs/src/joint/api/dia/Paper/events.html
docs/src/joint/api/dia/Paper/prototype/options/preventDefaultViewAction.html
src/dia/CellView.mjs
src/dia/ElementView.mjs
src/dia/LinkView.mjs
src/dia/Paper.mjs
src/dia/attributes/index.mjs
src/util/util.mjs
test/.eslintrc.js
test/jointjs/basic.js
test/jointjs/cell.js
test/jointjs/cellView.js
test/jointjs/connectors.js
test/jointjs/elements.js
test/jointjs/embedding.js
test/jointjs/links.js
test/jointjs/mvc.listener.js
test/jointjs/paper.js
test/jointjs/routers.js
test/utils.js
types/joint.d.ts

- **feat(dia.Paper)**: add `element:magnet:pointerdown`, `element:magnet:pointermove` and `element:magnet:pointerup`
New set of events are now triggered when the user interacts with a magnet. This together with `preventDefaultInteraction()` allows anyone to implement a custom magnet interaction *e.g. instead of creating a new link, it can create a link connected to an element*.
- **feat(dia.Paper)**: better event handling of form control elements inside foreign objects
When the form inputs are part of the element markup (inside the `<foreignObject>`) the default JointJS interaction should be prevented e.g you don't want the element to be moved while your focus is at a `<textarea>`. You need to be able to select the text inside instead.
- **feat(dia.Paper)**: add `preventDefaultViewAction` …

feat(dia.Paper): events handling improvements

---

demo/flowchart/index.js
docs/src/joint/api/connectors/intro.html
docs/src/joint/api/connectors/normal.html
docs/src/joint/api/connectors/rounded.html
docs/src/joint/api/connectors/straight.html
src/connectors/index.mjs
src/connectors/normal.mjs
src/connectors/rounded.mjs
src/connectors/straight.mjs
test/jointjs/connectors.js
types/joint.d.ts

Add a new connector `straight` which combines existing `normal` and `rounded` connectors with additional options to make path bevelled / with gaps at corners.
Different functionality is enabled via options:
- `opt.cornerType` = what to do at corners?
- `'point'` = default = connect path points with straight lines = `normal` connector functionality
- `'cubic'` = draw a cubic segment at points = `rounded` connector functionality
- `'line'` = draw a bevel segment at path points
- `'gap'` = draw empty space at path points
- `opt.cornerRadius` = how far away from corner point does the rounding/bevel/gap start and end?
- `10` by default (current default for rounded connector), ignored by `'point'`
- `opt.cornerPreserveAspectRatio` = if start and end are at different distances away from corner …

feat(connectors.straight): add new connector to combine normal, rounded, and bevelled connectors

---

src/dia/CellView.mjs
src/dia/ElementView.mjs
src/dia/LinkView.mjs
src/dia/Paper.mjs
src/dia/ToolsView.mjs
src/mvc/View.mjs
test/jointjs/dia/elementTools.js
test/jointjs/dia/linkTools.js
types/joint.d.ts

When the cell view was unmounted (`paper.options.viewport` returned `false`), it was removed from the DOM, but the tools attached to the cell view remained there.

fix(dia.Paper): hide tools when cell view is unmounted

---

demo/container/src/index.js
demo/container/src/joint.shapes.container.js

PR #2080 broke the Container demo by assuming that container.Child elements would have access to newly-written container.Parent method `fitAncestorElements()`. This caused errors to be written to the console whenever a container.Child element was dragged.
This PR fixes the problem by creating a new container.Base class and putting the `fitAncestorElements()` method there. The container.Child and container.Parent both extend this class.

fix(demo.Container): fix missing fitAncestorElements function for Child elements

---

src/dia/Paper.mjs
test/jointjs/dia/Paper.js

Throw an error when user trying to call `paper.unfreeze()` after removing the paper. Previously `unfreeze` was trying to run next frame which is not needed anymore.
This is to prevent unnecessary memory leaks (infinite `nextAnimationFrame` loop).

fix(dia.Paper): throw error when calling unfreeze after paper removal

---

src/dia/CellView.mjs
src/dia/HighlighterView.mjs
src/dia/LinkView.mjs
src/dia/Paper.mjs
src/dia/ToolsView.mjs
src/mvc/View.mjs
test/jointjs/dia/HighlighterView.js
test/jointjs/dia/Paper.js
test/jointjs/dia/elementTools.js
test/jointjs/dia/linkTools.js
types/joint.d.ts

When the cell view was detached (`paper.options.viewport` returned `false`) it was removed from the DOM, but the tools and highlighters attached to the cell view remained there.
- **fix(dia.ToolsView)**: is not removed from the DOM when the view is unmounted
- **fix(dia.HighlighterView)**: is not removed from the DOM when the view is unmounted
It reverts most of the changes introduced in this #2122 and approach this problem from a different angle.
- it resolves the same issue for highlighters (when the `highligher.options.layer` option is used).
- the #2122 mounted back the tool only if there was another update request along with insert request
- it redefines (while keeping it backwards compatible) the lifecycle cell view methods (`onMount(initial)`, `onDetach()`, `onRemove()`)
*Note: The …

fix(dia.Paper): hide tools and highlighters when cell view is detached

---

src/dia/CellView.mjs
test/jointjs/linkView.js

If changes are made to the connected element in the `link:connect` event handler, the link view must update taking these new changes (new size, new port position) into account.
The problem occurred only in `async` mode.
Fixes #2012.

fix(dia.CellView): fix link update if connected element changes at the same time the connection is made

---

docs/src/joint/api/dia/Paper/prototype/options/drawGridSize.html
src/dia/Paper.mjs
test/jointjs/paper.js
types/joint.d.ts

Add a new paper option `drawGridSize` to override the `gridSize` for drawing the grid (make the drawing of the grid independent from the snap to grid).
Resolves https://github.com/clientIO/joint/issues/2137

feat(dia.Paper): add drawGridSize option

---

src/dia/CellView.mjs

`cellView.getEventTarget()` now returns the target under the pointer even for `pointermove` and `pointerup` events for which pointer capture was set.
It allows the link arrowhead move interaction to be run with `mouseevents`, `touchevents` and `pointerevents`.
*Note: I couldn't  find a way how to fire and capture pointer events from script to add a sensible test.*

fix(dia.CellView): return correct target under the pointer for pointer events

---

docs/src/joint/api/dia/attributes/intro.html

- Fix misplaced `.` in `calc` docs

docs(dia.attributes): fix calc typo

---

demo/roi/css/roi.css

`position: fixed` is causing issues after the paper gets transformed (zoomed) in Safari.

fix(demo.ROI): fix zooming in Safari

---

types/joint.d.ts

This pull request:
- adds missing `opt` parameter in `dia.Link.labels` method signature
- adds TypeScript type predicates in `dia.Cell.isLink` and `dia.Cell.isElement`
- removes `isLink` and `isElement` TypeScript method signatures from `dia.Cell` descendants (as they were redundant)
Type predicates allow to write shorter code.
For example, following code:
```typescript
const cell = graph.getCells()[0];
if (cell.isLink()) {
const link = cell as Link;
link.disconnect();
}
```
can be simplified to this:
```typescript
const cell = graph.getCells()[0];
if (cell.isLink()) {
cell.disconnect();
}
```

fix(types): add missing Link.labels opt parameter and use type predicates in Cell.isLink and Cell.isElement

---

src/dia/HighlighterView.mjs
src/dia/ToolsView.mjs
test/jointjs/dia/HighlighterView.js
types/joint.d.ts

Prevent highlighter mounting and updates if it was attached to an unmounted cell view.
- it prevents displaying the standalone highlighter while the cell view is unmounted
- it improves the performance by not executing the update and mounting of the highlighter when not necessary
- the PR fixes a few typescript inconsistencies with inheritance mounting methods.
```js
const elementView = graph.getCell('element1').findView(paper);
paper.dumpViews({ viewport: () => false }); // hide all cell views
const highlighter = joint.dia.HighlighterView.add(elementView, 'root', id, { layer: dia.Paper.Layers.FRONT });
/* .... */
assert.notOk(highlighter.el.isConnected);
/* .... */
paper.dumpViews({ viewport: () => false }); // show the element view
assert.notOk(highlighter.el.isConnected); // only now …
```

fix(dia.HighlighterView): prevent highlighter mounting to unmounted cell views

---

src/dia/CellView.mjs
test/jointjs/cellView.js

The size and position of the `ref` node used in SVG custom attributes (e.g., the `calc()` expression) must only be transformed using transformations that are defined between the `ref` node and the common parent of the `ref` node and the current node to which we want to set the custom attribute.
Previously, it was transformed by all transformations between the `ref` node and the root of the cell view.
```js
elementModel.attr({
// set the size of rectangle `a` to the same size as `b`
a: {
x: 'calc(x)',
y: 'calc(y)',
width: 'calc(w)',
height: 'calc(h)',
}
});
```
```xml
<g transform="translate(11, 13)">
<rect @selector="b" x="1" y="2" width="3" height="4"/>
<rect @selector="a"/>
</g>
```
In this case, the reference bounding box can not be affected
by the `transform` attribute of the `<g>` …

fix(dia.CellView): fix to get correct ref node bounding box

---

src/dia/Paper.mjs
test/jointjs/paper.js

Prevent the paper from stopping other listeners of the `pointerup`  event attached on document from being called.
i.e. there is no need for calling [stopImmediatePropagation(https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation)] on `pointerup` (at least it is not covered by any test, nor it shows any issues during intensive testing).
The original [PR](https://github.com/clientIO/joint/commit/48db61cd85b9360558e365263fcaf0164908d1ff), which introduced the `evt.stopImmediatePropagation()` call, unfortunately did not go into a description of the reasons.
```js
QUnit.test('pointerup does not stop immediate propagation', function(assert) {
const view = new joint.mvc.View();
simulate.mousedown({ el: elRect });
// start listening to the document mousemove and mouseup …
```

fix(dia.Paper): allow immediate propagation on pointerup

---

tutorials/foreign-object.html

- Fix link in `foreignObject` tutorial. This link has already been fixed on `JointJS_Site` in the `3.7` documentation PR.

docs(tutorials): fix link in foreign object tutorial

---

src/dia/Cell.mjs
test/jointjs/basic.js
test/jointjs/cell.js
test/jointjs/graph.js
types/joint.d.ts

This pull request fixes the `cell.getEmbeddedCells` method. There was a bug that caused the result to always be sorted in a breadth-first manner, regardless of the value of the `breadthFirst` option.
It also adds a new internal option called `sortSiblings`, which enables sorting siblings by their `z` value.

fix(cell.getEmbeddedCells): fix the depth-first algorithm, add tests

---

demo/embedding/front-and-back.html
demo/embedding/front-and-back.js
docs/src/joint/api/dia/Element/prototype/toBack.html
docs/src/joint/api/dia/Element/prototype/toFront.html
src/dia/Cell.mjs
test/jointjs/basic.js
types/joint.d.ts

This pull request adds a new option called `foregroundEmbeds` to the `Cell.toFront` and `Cell.toBack` methods. By default, this option is set to `true`. When set to `true`, all the embedded cells will get a higher z-index than their parent element.
In pull request #2088, there was an unintentional breaking change in the `Cell.toFront` and `Cell.toBack` methods, which violated the following statement in the documentation:
> If `opt.deep` is `true`, all the embedded cells of this element will get higher `z` index than that of this element in a Breadth-first search (BFS) fashion.
This pull request addresses the issue by supporting both behaviors. Users can now decide whether to preserve the original stacking of a group or always have the embedded cells with a higher z-index than their …

feat(dia.Cell): add foregroundEmbeds option to the Cell.toFront and Cell.toBack

---

src/dia/LinkView.mjs

Fixed a bug when using `snapLinkSelf: true` the element was not targeted for connection.

fix(dia.LinkView): fix element detection when using snapLinkSelf: true

---

docs/src/joint/api/layout/PortLabel.md
src/layout/ports/portLabel.mjs
test/jointjs/elementPorts.js

Makes sure that `label.position.args.attrs` are correctly propagated for all PortLabel layout functions.
There is a bug in the `layout.PortLabel` implementation which ignores `label.position.args.attrs` for `inside`, `insideOriented`, `outside`, `outsideOriented`, `radial`, and `radialOriented` layouts, which is contrary to what the documentation says. This PR fixes the bug.
In addition, this PR fixes issues in the documentation stemming from mixing HTML and Markdown code.

fix(layout.PortLabel): fix passing of label.position.args.attrs in inside, outside, radial layouts

---

tutorials/links.html

- Update incorrect `href` values in links tutorial
- Open links in new window (consistent with other link behaviour in tutorials)

docs(tutorials): update incorrect href values in links tutorial

---

docs/src/joint/api/dia/Graph/constructor.html
docs/src/joint/api/dia/Paper/prototype/options/cellViewNamespace.html
tutorials/cell-namespace.html
tutorials/js/cell-namespace.js

Add `cell namespace` tutorial & update relevant options in `docs`
- add tutorial
- update graph option `cellNamespace` & paper option `cellViewNamespace` in docs
- fix typo in graph constructor docs - `cellNamespaceView` => `cellViewNamespace`. - Fixes #2270

docs(tutorials): add cell namespace tutorial

---

src/g/rect.mjs
test/geometry/rect.js

Rect.containsPoint is called many times with a Point instance as argument. Avoiding the new Point() call improves loading times significantly on large papers.
Our app uses Manhattan router with shapes and links. We've had performance issues when loading a larger paper, due to the time spent performing layout. One of the issues was that the routing logic calls `Rect.containsPoint` many, many times (thousands), and this function constructs a new Point every time it is called. But, the argument it gets is *already* a Point instance, so creating a copy just for the comparison is not necessary.

g.Rect: performance improvement when using Manhattan router with Rect shapes

---

yarn.lock

Before pushing a PR, `yarn install` has to be run. This is the reason why PR #2320 and commit fac8959 are failing.

chore: fix yarn.lock after commit fac8959 [dev]

---

types/joint.d.ts

Fixes incorrect paper layer name `LABELS`.

types(dia.Paper): fix labels layer name

---

src/dia/LinkView.mjs

When moving around elements and links that have doubleLinkTools: true in their LinkView but link length is short enough for the secondary tool to be hidden, the tool position is not updated. 
This causes miscalculations in paper size and paddings in various scenarios:
- the secondary tool starts at 0,0 and does not get moved when the LinkView is repositioned
- shortening the link while in bottom-right corner of a large paper hides the secondary tool. Then moving the link and all other elements towards top-left does not cause the paper to autoshrink because the tool is left behind at the position where it was before being hidden.

fix(dia.LinkView): prevent hidden doubleLinkTools to affect link bounding box

---

docs/src/joint/api/linkTools/Segments.html
src/linkTools/Segments.mjs

Fore more details, see [#2044](https://github.com/clientIO/joint/issues/2044).

fix(linkTools.Segments): throw explicit error when incompatible router in use

---

docs/src/joint/api/dia/CellView/prototype/findPortNode.html
docs/src/joint/api/dia/ElementView/prototype/findPortNode.html

Changed findPortNode function docs location to reflect typings.

docs: changed findPortNode function docs location to reflect typings

---

src/connectors/curve.mjs

Fixed wrong `TangentDirections.RIGHT` mapping for target directions.

fix(connectors.Curve): wrong enum mapping fix

---

src/shapes/standard.mjs

Unify cursor style for all `standard` links. Currently only `standard.Link` had its cursor set to `pointer`. This PR changes `standard.DoubleLink` and `standard.ShadowLink` to use the same cursor style.

fix(shapes.standard): fix cursor style on DoubleLink and ShadowLink

---

docs/src/joint/api/routers/manhattan.html
types/joint.d.ts

The manhattan router has an undocumented fallbackRouter option that defaults to "orthogonal". This PR exposes the option in ManhattanRouterArguments so it can be used by consumers and adds documentation for it.
In our app, we found it useful to provide a fallbackRouter that retries manhattan with more relaxed options before falling back to orthogonal. E.g. first manhattan tries with restricted start/end directions, while the second one uses all possible start/end directions.

types: expose fallbackRouter in ManhattanRouterArguments

---

src/V/index.mjs
test/vectorizer/vectorizer.js

PR allows to use of both kebab-case and camel-case attribute names when setting/reading/removing attributes to/from SVGNodes.
```js
vel.attr('strokeWidth', 2);
vel.attr({ strokeOpacity: 0.5, stroke: 'red' });
vel.removeAttr('strokeWidth');
```
The feature needs to be enabled with `V.supportCamelCaseAttributes = true;`.

feat(Vectorizer): add option to support camel case attributes

---

.travis.yml
package-lock.json
package.json

- Bump `node` version in `volta` to `18.18.2`
- Bump `npm` version in `volta` to `9.8.1`
Updating the `node` version to `18` meant we encountered the same breaking change in `node` 17 + `webpack`:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/73465262#73465262
As a result,`webpack`, `webpack-dev-server`, and `grunt-webpack` dependencies were updated. This explains the changes in `package-lock.json`. Otherwise, there would be no updates there.
`Travis` still has the same error with `node` 18, so the config hasn't been updated.

chore(deps): bump node version to 18

---

.travis.yml

- Bump `node` to version 18
- Bump `ubuntu` distribution to `20.04`
https://docs.travis-ci.com/user/reference/focal/
The following error occurs when updating to `node` 18, but with a lower `ubuntu` dist
https://github.com/nodejs/node/issues/42351
https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909
https://travis-ci.community/t/npm-err-spin-is-not-a-valid-npm-option/13797

chore(Travis): update node and ubuntu dist

---

demo/right-angle-playground/css/style.css
demo/right-angle-playground/index.html
demo/right-angle-playground/src/index.js
src/routers/rightAngle.mjs
test/jointjs/routers.js
types/joint.d.ts

Until now the `RightAngle` router didn't use the vertices that were provided. This change allows users to define vertices through which the link is supposed to go. The `RightAngle` router itself works the same way as it did, the only difference is that it takes in account the provided vertices and finds route between them.
A simple upgrade of the algorithm that enables you to use the `RightAngle` router in more ways.

feat(routers.RightAngle): support user defined vertices

---

docs/src/joint/api/shapes/standard/InscribedImage.html

- Fix typo in `standard.InscribedImage` code example.

docs(standard.InscribedImage): fix typo in code example

---

src/dia/Paper.mjs
test/jointjs/paper.js
types/joint.d.ts

In case a custom event is bound to the label of the link propagate it, so the appropriate listeners can react to it accordingly.
Related to the changes from #2110.
Custom events that were declared on the label of a link like this:
```js
const link = new joint.shapes.standard.Link({
source: { x: 50, y: 50 },
target: { x: 300, y: 70 },
labels: [{
markup: [
{
tagName: 'rect',
selector: 'labelBody'
}, {
tagName: 'text',
selector: 'labelText'
}
],
attrs: {
labelText: {
text: 'Label',
pointerEvents: 'none',
},
labelBody: {
ref: 'text',
width: 'calc(w)',
height: 'calc(h)',
fill: '#ffffff',
stroke: 'black',
event: 'link:label:pointerdown',
}
},
}]
});
```
were not triggered after the `pointerdown` event was executed.

feat(dia.Paper): custom events on link label

---

packages/joint-core/package.json

Remove lodash from `dependencies` in `package.json` (but keep it in `devDependencies` for now). This is part of our initiative for no-dependency JointJS.
This PR finishes the work started by #2115 now that #2386 has been merged

chore: remove lodash from dependencies [dev]

---

packages/joint-core/css/layout.css

The `basic` shapes have been removed, but the CSS remains in this [PR](https://github.com/clientIO/joint/pull/2422).

fix(css): remove leftover basic shapes CSS

---

packages/joint-core/css/layout.css
packages/joint-core/docs/src/joint/api/highlighters/opacity.html
packages/joint-core/src/highlighters/opacity.mjs
packages/joint-core/src/highlighters/stroke.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js
packages/joint-core/types/joint.d.ts

Add `alphaValue` to `opacity` highlighter to control the value of transparency.
Opacity no longer adds a CSS class to the node. It is set to `opacity` via the inline CSS style attribute. If `opacity` was set on a node via the inline attribute, the original value will be removed when the highlighter is removed.
If I add a highlighter to such a node, the `opacity` property will be removed along with the highlighter.
```svg
<rect style="opacity: 0.5"/>
```
In this case, everything works as before.
```svg
<rect opacity="0.5"/>
```
If you need to support the `opacity` in the inline style attribute, use `highlighter.addClass` instead.
```js
highlighters.addClass.add(cellView, selector, id, { className: 'highlight-opacity' });
```
```css
.highlight-opacity { opacity: 0.3 }
```

feat(highlighters.Opacity)!: add alphaValue option

---

packages/joint-core/demo/flowchart/index.js
packages/joint-core/demo/links/src/custom-links.js
packages/joint-core/demo/links/src/links.js
packages/joint-core/docs/src/vectorizer/api/V/attributeNames.html
packages/joint-core/src/V/index.mjs
packages/joint-core/src/highlighters/mask.mjs
packages/joint-core/test/vectorizer/vectorizer.js
packages/joint-core/tutorials/custom-links.html
packages/joint-core/types/vectorizer.d.ts

The PR enables the camel case attribute support by default and makes the `attributeNames` property public.
The `supportCamelCaseAttributes` property remains private.
Before:
```js
V('g').attr('myAttribute', 'value') // <g myAttribute="value"/>
```
Now:
```js
V('g').attr('myAttribute', 'value') // <g my-attribute="value"/>
```
Allows you to use camel case attribute names anywhere in JointJS. e.g `targetMarker`, `mvc.View.prototype.attributes`
If you need any attribute to stay camel cased, you have to define it through `attributeNames` property.
```js
V.attributeNames['myAttribute'] = 'myAttribute';
V('g').attr('myAttribute', 'value') // <g myAttribute="value"/>
```

feat(Vectorizer)!: support camel case attributes, add attributeNames static property

---

packages/joint-core/demo/archive/org/src/org.js
packages/joint-core/demo/links/src/pipes.js
packages/joint-core/demo/ports/ports.html
packages/joint-core/docs/demo/layout/Port/port.html
packages/joint-core/docs/demo/layout/Port/portRotationComp.html
packages/joint-core/docs/demo/layout/PortLabel/portLabel.html
packages/joint-core/docs/src/joint/api/dia/Paper/prototype/options/perpendicularLinks.html
packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/links.js
packages/joint-core/types/joint.d.ts

- remove deprecated `dia.Paper.prototype.options.perpendicularLinks`.
Instead of using `perpendicularLinks: true`, set the [defaultAnchor](https://resources.jointjs.com/docs/jointjs/v3.7/joint.html#dia.Paper.prototype.options.defaultAnchor) paper option to [perpendicular](https://resources.jointjs.com/docs/jointjs/v3.7/joint.html#anchors.perpendicular) connection point.
```js
paper.options.defaultAnchor = { name: 'perpendicular' };
```

refactor(dia.Paper)!: remove deprecated perpendicularLinks option

---

packages/joint-core/demo/archive/fsa/src/fsa.js
packages/joint-core/demo/links/src/links.js
packages/joint-core/docs/demo/layout/DirectedGraph/js/index.js
packages/joint-core/docs/src/joint/api/connectors/smooth.html
packages/joint-core/docs/src/joint/api/dia/Link/events.html
packages/joint-core/docs/src/joint/api/dia/Link/prototype/connector.html
packages/joint-core/docs/src/joint/api/dia/Link/prototype/router.html
packages/joint-core/docs/src/joint/api/routers/orthogonal.html
packages/joint-core/src/connectors/jumpover.mjs
packages/joint-core/src/dia/Link.mjs
packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/test/jointjs/routers.js
packages/joint-core/types/joint.d.ts

- removing the deprecated `smooth` attribute (syntactic sugar for the `smooth` connector).
- removing the obsolete `manhattan` attribute (syntactic sugar for `orthogonal` router).
Before:
```js
link.set('smooth', true);
link.set('manhattan', true);
```
Now:
```js
link.connector('smooth'); // or link.set('connector', { name: 'smooth' });
link.router('orthogonal'); // or link.set('router', { name: 'orthogonal' });
```

refactor(dia.Link)!: remove smooth and manhattan attributes

---

packages/joint-core/docs/src/joint/api/highlighters/stroke.html
packages/joint-core/src/highlighters/stroke.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js
packages/joint-core/types/joint.d.ts

Add `nonScalingStroke` option to `stroke` highlighter to add `vector-effect=non-scaling-stroke` to the highlighter.
It's a visual breaking change because the highlighter now scales with the paper (when the zoom level of the paper changes, the stroke thickness changes too).
Before:
```js
highlighters stroke.add(elementView, 'body', id);
```
Now:
```js
highlighters stroke.add(elementView, 'body', id, { nonScalingStroke: true });
```

feat(highlighters.stroke)!: add nonScalingStroke option

---

packages/joint-core/src/linkTools/Button.mjs

As per documentation "The names of built-in link tools are kebab-case versions of their class names ".
This was not the case for the `linkTools.Remove` and `elementTools.Remove` buttons.
You may have styled the `Remove` button using CSS in your app.
Before:
```css
.joint-tool[data-tool-name="button"] circle {
fill: #333;
}
```
Now:
```css
.joint-tool[data-tool-name="remove"] circle {
fill: #333;
}
```

refactor(linkTools, elementTools)!: change Remove tool name

---

packages/joint-core/docs/src/joint/api/dia/Cell/constructor.html
packages/joint-core/src/dia/Cell.mjs
packages/joint-core/test/jointjs/cell.js
packages/joint-core/types/joint.d.ts

The class array default attributes are now overridden instead of merged. A new option to support previous behavior was added. 
The reason for this change is to make it easier to instantiate the class and define the initial attributes, which are arrays.
```js
const MyRect = joint.shapes.standard.Rectangle.define('Rect', { array: [1,2] });
const rect1 = new MyRect({ array: [3] });
console.log(rect1.get('array')); // [3] array was overridden
const rect2 = new MyRect({ array: [3] }, { mergeArrays: true });
console.log(rect2.get('array')); // [3,2] array was merged
```

feat(dia.Cell)!: add mergeArrays options to constructor

---

packages/joint-core/src/dia/Paper.mjs

Change how the default filters are rendered (change the coordinate system of the filters from `objectBoundingBox` to `userSpaceOnUse`).
This fixes applying filters to shapes with `0` width or height (such as horizontal/vertical links).
If you need your filter to look the same as in the previous version, you can add `attrs` object to your filter as shown below.
```js
element1.attr('body/filter', {
// for backwards compatibility
attrs: {
filterUnits: 'objectBoundingBox',
x: -1,
y: -1,
width: 3,
height: 3
},
name: 'dropShadow',
args: {
dx: 2,
dy: 2,
blur: 3
}
});
```

fix(attributes.filter)!: fix filter attribute for links

---

packages/joint-core/src/mvc/Collection.mjs
packages/joint-core/src/mvc/index.mjs
packages/joint-core/src/util/utilHelpers.mjs
packages/joint-core/test/jointjs/mvc.collection.js
packages/joint-core/types/joint.d.ts

Update `mvc.Collection` methods and relevant `types`.
Methods added:
- `each`
- `filter`
- `includes`
- `isEmpty`
- `map`
- `reduce`
Methods removed:
- `pluck`
---
This PR fixes the `mvc.Collection` tests. The `mvc.Events` tests were copied to the `mvc.collection.js` test file by accident, so this just reverses that. 
Around 14 instances of `pluck` were removed from the test file, and replaced with `map`.
`collection.pluck('id')` => `collection.map((model) => model.get('id'))`
The PR also removes the instances of `Array.from` from `mvc.Collection`.
---
The PR also fixes exposing `extend` and `addMethodsUtil` from `mvcUtils` to the user.
- Add tests for methods
- Document methods

feature(mvc.Collection): update collection methods

---

packages/joint-core/types/joint.d.ts
packages/joint-shapes-general-tools/src/RadiusControl.ts

Improve the return type of the `findNode()` method to avoid the use of `as unknown`.

types(dia.CellView): improve the findNode return type specificity

---

packages/joint-core/src/mvc/Dom/Dom.mjs
packages/joint-core/src/mvc/Dom/methods.mjs
packages/joint-core/types/joint.d.ts

- add missing `filter()` method used by `util.seAttributesBySelector()`
- `$el.html(number)`  converts the number to a string and sets the element content
- add `detach()` method as an alternative to `remove()` which does not remove the attached  events
- `$.event.has` now accepts the second attribute (type of the event)
- introduce the `$Element` type, which represents DOM elements that can be passed to the `$()` function. Many functions still use `$` internally, and this type describes what types are accepted

fix(mvc.$): add missing filter() method, fix html() to accept numbers

---

packages/joint-core/src/mvc/Dom/Dom.mjs
packages/joint-core/src/mvc/Dom/animations.mjs
packages/joint-core/src/mvc/Dom/events.mjs
packages/joint-core/src/mvc/Dom/index.mjs
packages/joint-core/src/mvc/Dom/methods.mjs
packages/joint-core/src/mvc/Dom/props.mjs
packages/joint-core/test/jointjs/index.html
packages/joint-core/test/jointjs/mvc.Dom.js
packages/joint-core/test/utils.js
packages/joint-core/types/joint.d.ts

Improve the `mvc.$.fn` methods not to introduce breaking change unnecessarily
- fix `html()` method typos
- return `this` to allow chaining
- add `toggleClass()`, `prop()`, `height()`, `width()`, `children()`, `clone()`
- add other property method wrappers such as `val()`, `scrollTop()`
- add `animation()` and `stop()`
- add `offset()` and `position()`
- add a few tests

feat(mvc.$): update methods for better backwards compatibility

---

packages/joint-core/demo/paper/src/paper.js
packages/joint-core/docs/src/joint/api/dia/Paper/prototype/clearGrid.html
packages/joint-core/docs/src/joint/api/dia/Paper/prototype/drawGrid.html
packages/joint-core/docs/src/joint/api/dia/Paper/prototype/setGrid.html
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/src/dia/PaperLayer.mjs
packages/joint-core/src/dia/layers/GridLayer.mjs
packages/joint-core/test/jointjs/paper.js
packages/joint-core/types/joint.d.ts

The grid is now rendered as an SVG document inside the paper layer.
- Paper transformations are applied to it in the same way as to cells, i.e. the grid does not need to be completely redrawn when the paper is transformed (unlike the previous solution with HTMLDivElement CSS background).
- The grid can now also be easily exported as SVG/PNG.
API change. Drop `drawGrid()` and `clearGrid()` methods.
Before:
```js
// show the grid
paper.setGrid('mesh');
paper.drawGrid();
// remove the grid
paper.clearGrid();
// change color of grid
const paper = new dia.Paper({ drawGrid: { name: 'dots', color: 'red' }});
paper.drawGrid({ color: 'blue' });
// paper.options.drawGrid value
const paper = new dia.Paper({ drawGrid: { name: 'dots' }});
paper.drawGrid({ name: 'mesh; }); // paper.options.drawGrid === …
```

refactor(dia.Paper)!: add SVG grid layer

---

packages/joint-core/demo/.eslintrc.js
packages/joint-core/demo/custom-embedding/README.md
packages/joint-core/demo/custom-embedding/custom-embedding.js
packages/joint-core/demo/custom-embedding/index.html
packages/joint-core/demo/ts-demo/.gitignore
packages/joint-core/demo/ts-demo/custom.ts
packages/joint-core/demo/ts-demo/index.ts
packages/joint-core/demo/ts-demo/shape.ts
packages/joint-core/grunt/config/aliases.js
packages/joint-core/grunt/config/copy.js
packages/joint-core/test/jointjs-nodejs/index.js
packages/joint-core/test/ts/index.test.ts
packages/joint-core/test/ts/mvc.listener.test.ts
packages/joint-core/test/ts/toolsView.test.ts
packages/joint-core/test/ts/vectorizer.test.ts

- typescript tests import joint from joint-core package (`../../`)
- demo/ts-demo imports joint from joint-core package (`../../`)
- grunt logic to copy joint.js and joint.d.ts files into `demo/ts-demo/vendor/joint` is no longer necessary
- demo/custom-embedding uses `build/joint.js` instead of `build/joint.webpack-bundle.js` (there was no reason to use the webpack bundle and it was inconsistent with other demos)
Thanks to #2473, it is no longer necessary to build jointjs in order to be able to use it in typescript code.

refactor: Use joint directly in typescript tests and in ts-demo

---

packages/joint-core/types/joint.d.ts

The individual options in `debounce` methods should not be mandatory.
```ts
util.debounce(fn, 100, { leading: true }); // `maxWait` and `trailing` are optional
```

types(util): make debounce options optional

---

packages/joint-core/src/linkTools/Vertices.mjs
packages/joint-core/src/mvc/Dom/methods.mjs
packages/joint-core/src/mvc/Dom/vars.mjs

Make sure all the event listeners and data are removed from the DOM nodes if they are removed using `mvc.Dom`.
This PR just fixes behavior to match jQuery removal functionality.

fix(mvc.Dom): remove event listeners on element removal;  fix(linkTools.Vertices): fix to fire mouseleave event when redundancyRemoval is disabled

---

packages/joint-core/demo/archive/petri-nets/src/pn.js
packages/joint-core/demo/bandwidth/src/bandwidth.js
packages/joint-core/demo/container/src/index.js
packages/joint-core/demo/devs/src/shapes.devs.js
packages/joint-core/demo/expand/index.js
packages/joint-core/demo/fsa/src/fsa.js
packages/joint-core/demo/graph.js
packages/joint-core/demo/performance/async.js
packages/joint-core/demo/ports/dynamic.js
packages/joint-core/demo/ports/ports2.js
packages/joint-core/docs/src/joint/api/connectionPoints/intro.html
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/connectors.js
packages/joint-core/test/jointjs/routers.js
packages/joint-core/tutorials/js/ports-basic-groups.js
packages/joint-core/tutorials/js/ports-basic.js
packages/joint-core/tutorials/js/ports-layout.js
packages/joint-core/tutorials/js/ports-link-snapping.js
packages/joint-core/tutorials/js/ports-links.js
packages/joint-core/tutorials/js/ports-mark-available.js
packages/joint-core/tutorials/js/ports-restrictions.js
packages/joint-core/tutorials/js/testing-e2e-playwright.js

Change the value of the `defaultConnectionPoint` option to `boundary` to make the diagrams more visually appealing by default.
To use the `bbox` connection point set the `defaultConnectionPoint` paper option as shown below:
```js
new dia.Paper({
/* ... */
defaultConnectionPoint: { name: 'bbox' }
});
```

refactor(dia.Paper)!: change the default connection point to 'boundary'

---

packages/joint-core/src/dia/Paper.mjs

For consistency, all events fired on paper are passed native events wrapped in the `mvc.$.Event` wrapper.
Before:
```js
paper.on('paper:pinch', (evt) => console.log('this is a native event', evt));
```
Now:
```js
paper.on('paper:pinch', (evt) => console.log('this is a native event', evt.originalEvent));
```

fix(dia.Paper)!: fix `paper:pinch` dispatched event type

---

packages/joint-core/src/mvc/Dom/methods.mjs
packages/joint-core/src/mvc/Dom/props.mjs
packages/joint-core/test/jointjs/mvc.Dom.js

Allow passing properties to the `attr()` method of `mvc.$` object for backwards compatibility.
```js
mvc.$(el).attr({ disabled: true }); // sets property `disabled` to `true`
```

fix(mvc.Dom): allow properties to be passed to attr() method

---

packages/joint-core/docs/src/joint/api/dia/Cell/prototype/parent.html
packages/joint-core/types/joint.d.ts

Remove the `Cell.parent(id)` setter from type definitions and documentation.
`Cell.parent(id)` method is not intended to be used as a way to embed cells. To eliminate the confusion it was decided to remove it from type definitions and documentation.
Related to #2107.
In case you were using the `Cell.parent(cell)` as a solution to embed cells, use the `Cell.embed(cell)` instead.
```js
const parent = joint.shapes.standard.Rectangle();
const child = joint.shapes.standard.Rectangle();
parent.embed(child);
```

fix(dia.Cell): remove setter from prototype in docs and types

---

packages/joint-core/types/index.d.ts

Fixes joint-plus package types resolutions, when using Typescript version lower then 4.9

fix(types): lower ts versions compatibility

---

packages/joint-core/demo/archive/joint.dia.LegacyLinkView.js
packages/joint-core/demo/marey/src/marey.js
packages/joint-core/docs/demo/dia/Paper/interactive/labelMove.html
packages/joint-core/docs/demo/dia/Paper/interactive/labelMoveSnapLabels.html
packages/joint-core/docs/demo/dia/Paper/interactive/linkMove.html
packages/joint-core/docs/src/joint/api/dia/LinkView/intro.html
packages/joint-core/docs/src/joint/api/dia/LinkView/prototype/addLabel.html
packages/joint-core/docs/src/joint/api/dia/LinkView/prototype/addVertex.html
packages/joint-core/docs/src/joint/api/dia/LinkView/prototype/getLabelPosition.html
packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/tutorials/js/link-labels-interaction-snap-labels.js
packages/joint-core/tutorials/js/link-labels-interaction.js
packages/joint-core/tutorials/link-labels.html
packages/joint-core/types/joint.d.ts

Remove legacy references to options (`dia.LinkView` and `interactivity`) across lib. Finishes work started by #2446

refactor: remove legacy unused linkView and interactivity options

---

packages/joint-core/tutorials/custom-elements.html

Sync `custom-element` tutorial with video inclusion.
- Include youtube video in `custom-element` tutorial. This means this tutorial is in sync with `JointJS_Site`
- Closes https://github.com/clientIO/joint/pull/2393

chore(tutorials): include video in custom elements tutorial

---

packages/joint-core/grunt/config/aliases.js
packages/joint-core/grunt/config/copy.js
packages/joint-core/grunt/config/shell.js
packages/joint-core/grunt/config/uglify.js
packages/joint-core/grunt/resources/core.js
packages/joint-core/grunt/resources/esm.js
packages/joint-core/joint.mjs
packages/joint-core/package.json
packages/joint-core/rollup.config.js
packages/joint-core/test/jointjs/require.js

Removes `joint.core.js` and `joint.core.min.js` from `dist/`, and the associated logic

chore(dist): do not distribute joint.core.js + joint.core.min.js

---

packages/joint-core/tutorials/installation.html

- Update package name in installation instructions to `@joint/core` in `installation` tutorial.
In the `changelog`, `hello-world` tutorial, and `installation` tutorial there is a CDN link of:
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/jointjs/4.0.0/joint.js"></script>
```
I am currently not sure what the link should be.

docs(tutorials): update installation instructions

---

packages/joint-core/tutorials/installation.html

- Update CDN link in `installation` tutorial. The CDN links are already updated in the `JointJS_Site` docs release PR. https://github.com/clientIO/JointJS_Site/pull/215

docs(tutorials): update CDN link in installation tutorial

---

packages/joint-core/src/dia/attributes/text.mjs
packages/joint-core/test/jointjs/dia/attributes.js

The `text-wrap` attribute takes external CSS and inherited styles into account when computing the line breaks (previously only explicit inline attributes were considered).
The `text-wrap` worked properly only when the font attributes were set explicitly.
```html
<text font-size="12">A text to wrap</text>
```
This PR adds support for external CSS: 
```html
<style>
text { font-size: 12px; }
</style>
...
<text>A text to wrap</text>
```
_Note: Thanks to https://github.com/clientIO/joint/pull/2459, all font attributes are evaluated and set before `text-wrap`, so it is safe to use the `getComputedStyle()` method._
Fixes https://github.com/clientIO/joint/issues/2295.

fix(attributes): text-wrap takes external CSS into account

---

packages/joint-core/docs/src/joint/api/dia/Paper/prototype/getFitToContentArea.html
packages/joint-core/test/ts/index.test.ts
packages/joint-core/types/joint.d.ts

It's currently not possible to override the `allowNewOrigin` to its default. This PR makes it possible to pass `false` for the paper origin to remain at `0,0` in *TypeScript*.
Note that this has always been possible in *JavaScript*, and this PR just changes the types and updates the documentation to make it clear.
```ts
// before
paper.getFitToContentArea({ allowNewOrigin: 'negative' | 'positive' | 'any'  })
// after
paper.getFitToContentArea({ allowNewOrigin: false | 'negative' | 'positive' | 'any'  })
```
The problem was evident in the paper scroller.
```js
const scroller = new ui.PaperScroller({
/* ... */
contentOptions: {
allowNewOrigin: false // the paper scroller default for `allowNewOrigin` is `positive`
}
})
```

types(dia.Paper): allow disabling allowNewOrigin option

---

packages/joint-core/tutorials/hello-world.html
packages/joint-core/tutorials/installation.html

Update tutorial CDN links to `jsdelivr`, because package has not been added to `cdnjs` yet.
https://www.jsdelivr.com/package/npm/@joint/core

docs: update tutorial CDN links

---

packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/dia/Paper.js

This ensures that when `Paper.resetViews()` is called, any pending animation frame request is not leaked.
When `resetViews()` calls `_resetUpdates()` it's possible that there's an animation frame request, but `_resetUpdates()` was not checking for this and cancelling any such request, potentially causing `updateViewsAsync()` to be called when it shouldn't be.
This can cause unexpected behavior if the paper was frozen, or cause an error to be thrown if the paper is removed (since `updateViewsAsync()` with throw in such a case).

fix(dia.Paper): don't leak animation frame request

---

packages/joint-core/types/joint.d.ts

This was mistakenly put on `ToolsView`, but it's actually on `ToolView`

fix(types) fix simulateRelatedView type

---

packages/joint-core/types/joint.d.ts

Instead of passing a generic `Element`/`Link` type to `CellViewGeneric` this provides an optional generic to pass the model type. It would be used like the following:
```typescript
interface CustomElementAttributes extends dia.Element.Attributes {
custom_attribute: string,
}
class CustomElement extends dia.Element<CustomElementAttributes> {
// ...
}
class CustomElementView extends dia.ElementView<CustomElement> {
// ...
}
```
Default behaviour is the current behaviour. The change is fully backwards compatible.
- this.model.get(...) is checked against attributes of the model
- return value is typed instead of `any`
- language server knows about possible keys
- No longer throws errors ("... implicitely has any type") when used with typescript
- Removes manual overhead of hard coding types …

types: fix untyped model when using ElementView/LinkView

---

packages/joint-core/types/joint.d.ts

- add protected methods for `elementTools.Button` to allow class extension
- properly specify the link end in `anchor` and `connectionPoint` function
- add public `startArrowheadMove()` to the `LinkView` class (until a proper API to initiate a link's dragging is implemented).

type: various small fixes

---

packages/joint-core/docs/demo/highlighters/js/mask.js

Fix a failing example in the documentation for highlighters (invalid `ref` attribute value).

docs: fix highlighter example

---

packages/joint-core/src/linkTools/Arrowhead.mjs
packages/joint-core/test/jointjs/dia/linkTools.js

When the user drags the arrowhead of a link (either by dragging the port or using the `linkTools.Arrowhead` tool), the following events are triggered on paper:
```
'link:pointerdown' (1)
'link:pointermove' (0+)
link:pointerup' (1)
```
However, in the case of `linkTools.TargetArrowhead` and `linkTools.SourceArrowhead` the `link:pointerdown` event was missing.
*Note: it applies to `cell:pointerdown` event too.*

fix(linkTools.Arrowhead): fix to trigger missing paper pointerdown event

---

.github/ISSUE_TEMPLATE/bug.yml

Update `bug` github issue template. Highlight "Steps to reproduce".

chore(github): update github bug report template

---

packages/joint-core/README.md

Fix broken Travis CI build status icon in README.md.

chore: fix travis CI badge

---

packages/joint-core/src/dia/layers/GridLayer.mjs
packages/joint-core/test/jointjs/paper.js

Fixes https://github.com/clientIO/joint/issues/2648
Fix to generate unique ids for paper `<pattern/>` elements to allow multiple paper instances draw a grid.
By definition, element `id` [must be unique within a single document](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).
Because the pattern identifiers were unique within the paper instance (and not globally), only one of the grids was displayed.

fix(dia.Paper): ensure grid pattern ids are unique

---

packages/joint-core/package.json
packages/joint-decorators/package.json
packages/joint-layout-directed-graph/package.json
packages/joint-shapes-general-tools/package.json
packages/joint-shapes-general/package.json

Add a `prepublishOnly` script to prevent publishing via NPM. `prepublishOnly` scripts are called by NPM before publish when `npm publish` is called. These scripts are ignored by Yarn, allowing us to call `yarn npm publish` as intended.
Publishing via `npm publish` does not resolve `workspace:` protocols in `dependencies`, which leads to an error when our users try to install our packages.
Technically, this change is not necessary for `joint-core` (since it does not have any `workspace:` protocol dependencies), but I did it for it too for consistency.

chore(package.json): prevent publishing via NPM

---

packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/src/env/index.mjs

Safari has a bug where any change after the first render is not reflected in the DOM.
https://bugs.webkit.org/show_bug.cgi?id=268376
This a fix to workaround the issue.
Fixing https://github.com/clientIO/joint/issues/2328.

fix(dia.LinkView): fix missing arrowheads in Safari

---

packages/joint-core/test/ts/index.test.ts
packages/joint-core/types/joint.d.ts

It was not possible to set partial attributes using `prop()` method or when constructing a new cell in *TypeScript*.
```ts
rectangle.prop({ size: { width: 100 }});
new joint.shapes.standard.Rectangle({
position: { x: 100 },
});
```

types(dia.Cell): allow partial attributes with prop() and constructor()

---

packages/joint-core/demo/html/css/html.css
packages/joint-core/demo/html/src/html.js
packages/joint-core/demo/html/src/joint.shapes.html.js

- add `onMount()` and `onDetach()` to `HTMLElementView` in order to support virtualization
- remove unnecessary `guard()` paper option.
- add comments about usability and stacking order of links

feat(demo): update HTML demo for v4

---

CHANGELOG
examples/decorators/package.json
examples/dwdm/package.json
examples/fta-js/package.json
examples/isometric/package.json
examples/layout-directed-graph/package.json
examples/libavoid/package.json
examples/list/package.json
examples/shapes-general/package.json
examples/tree-of-life/package.json
package.json
packages/joint-core/demo/custom-shapes/package.json
packages/joint-core/demo/elk/package.json
packages/joint-core/demo/rough/package.json
packages/joint-core/demo/tree-shake/package.json
packages/joint-core/demo/ts-demo/package.json
packages/joint-core/demo/vuejs/package.json
packages/joint-core/package.json
packages/joint-core/tutorials/hello-world.html
packages/joint-core/tutorials/installation.html
packages/joint-decorators/package.json
packages/joint-layout-directed-graph/package.json
packages/joint-shapes-general-tools/package.json
packages/joint-shapes-general/package.json

* update **HTML demo** in alignment with `v4` (2f3282146344d5637f729dfde8385106bb4190a8)
* **dia.LinkView** - fix missing arrowheads in Safari (bccc2ef5605a1a090f7dda0f999ec1757b3ca173)
* **dia.attributes** - fix to take the inline font attributes into account in `textWrap`(66442ad55ea5b3a27509828f8e1204beec5d8f3c)

Release v4.0.4

---

packages/joint-core/src/dia/Graph.mjs
packages/joint-core/test/jointjs/graph.js

Make sure the `graph` reference is removed from the cells after `resetCells()` call.
```ts
const el = new shapes.standard.Rectangle();
graph.addCell(el);
assert.ok(el.graph === graph);
graph.resetCells([]); // now removes the `graph` references
assert.ok(!el.graph);
```

fix(dia.Graph): remove graph reference from cells after resetCells()

---

packages/joint-core/types/joint.d.ts

Fix incorrect TS definition of a few paper methods.
- remove `progress` option from `dumpViews()`
- remove `progress` option from `updateViews()`
- add `priority` property to `updateViews()` return value
---
See https://github.com/clientIO/joint/discussions/2695.

types(dai.Paper): fix dumpViews() and updateViews() signature

---

packages/joint-core/src/dia/HighlighterView.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js

A new static method added to `dia.HighlighterView` as there was no way to get all the highlighters of a certain type and ID from the paper.
https://docs.jointjs.com/api/dia/HighlighterView/
Get an array of all highlighters on the `paper`, which are instances of this class. If an `id` is provided, get only the highlighters with given `id` on the `paper`.

feat(dia.HighlighterView): add static getAll() method

---

packages/joint-core/src/mvc/ViewBase.mjs
packages/joint-core/test/jointjs/mvc.view.js

Allow `style` attribute to be set via options.
All other properties can be set either as a class property or as a constructor option.
```ts
// Already supported
(new mvc.View.extend({ style: { color: 'red' }})).el.style.color === 'red';
```
```ts
// Supported after this PR
(new mvc.View({ style: { color: 'red' }})).el.style.color === 'red'
```
The documentation missing not only the `style` property but also `events` and `constructor()`.
https://docs.jointjs.com/api/mvc/View/#properties
A hash of CSS properties that will be set as inline style on the view's el (`color: red;`, etc.), or a function that returns such a hash.
There are several special options that, if passed, will be attached directly to the view: `model`, `collection`, `el`, `id`, `className`, `tagName`, `attributes`, `style` …

fix(mvc.View): set style via options

---

examples/libavoid/src/avoid-router.js
packages/joint-core/docs/src/joint/api/dia/Element/prototype/getPortGroupNames.html
packages/joint-core/src/dia/ports.mjs
packages/joint-core/test/jointjs/elementPorts.js
packages/joint-core/types/joint.d.ts

Add a convenient method for those who want to iterate over all port groups.
```ts
element.getPortGroupNames().forEach(group => {
const groupPortPositions = element.getPortsPositions(group);
/* ... */ 
});
```
Returns an array of port group names of the element.
It returns all port group names defined on the element regardless of whether the port group has any ports or not.

feat(dia.Element): add getPortGroupNames()

---

packages/joint-core/demo/links/src/links.js
packages/joint-core/src/linkTools/Vertices.mjs
packages/joint-core/test/jointjs/dia/linkTools.js
packages/joint-core/types/joint.d.ts

The current solution with the `linkTools.Vertices` and its extra path overlay has several disadvantages. For example, it was not possible to move labels and create vertices at the same time (because an invisible path was rendered above the link and the labels).
This PR allows you to choose an existing node from the link view to serve as an interactive hit area for creating vertices.
https://docs.jointjs.com/api/linkTools/#vertices
Can the user add new vertices (by clicking a segment of the link)?
|Value|Description|
|--|--|
|`false`| The user can not add new vertices. |
|`true`|  An invisible path is rendered above the link which creates vertices upon interaction with it.  |
| `{}` |  See `VertexAddingOptions` | 
|Option|Description|
|--|--|
|`interactiveLinkNode: string;` | A `selector` …

feat(linkTools.Vertices): add vertexAdding interactiveLinkNode option

---

packages/joint-core/src/routers/rightAngle.mjs
packages/joint-core/test/jointjs/routers.js

This PR introduces fixes to the right-angle router. The fixes include changes to the connection of vertices, handling the first and last vertex, creating a loop for the last vertex in case the segments overlap, and finding shorter routes alongside the horizontal and vertical sides of a shape.
This PR improves right-angle router in order for it to give better results.
| Before | After |
|--------|------|

fix(routers.RightAngle): various problems

---

packages/joint-core/types/joint.d.ts

Add missing `getAll()` static method TS definition from [PR](https://github.com/clientIO/joint/pull/2704).

types(dia.HighlighterView): add missing getAll() static method

---

packages/joint-core/src/linkTools/Arrowhead.mjs
packages/joint-core/test/jointjs/dia/linkTools.js

This PR makes sure that all active batches are closed at the end of the drag arrowhead interaction.
https://github.com/clientIO/joint/pull/2625 fixed triggering of `pointerdown` event. This caused the `pointer` batch to be (correctly) triggered, but due to not passing event data to subsequent events (`pointermove` & `pointerup`), the `pointer` batch closure was never invoked.
Fixes [issue](https://github.com/clientIO/joint/issues/2719).

fix(linkTools): fix pending batch for TargetArrowhead and SourceArrowead

---

packages/joint-core/src/dia/Cell.mjs
packages/joint-core/src/dia/Graph.mjs
packages/joint-core/src/util/util.mjs
packages/joint-core/test/jointjs/cell.js
packages/joint-core/test/jointjs/core/util.js
packages/joint-core/test/jointjs/graph.js
packages/joint-core/types/joint.d.ts

This PR includes changes to the `dia.Cell.toJSON()`, now accepting two new options.
- `opt.ignoreDefaults` (_default_ `['attrs']`) - accepts an array of attribute names to be compared to the defaults, additionally setting this option to `false` will result in returning all of the attributes without comparing them, while setting it to `true` results in a comparison of all the attributes with defaults
- `opt.ignoreEmptyAttributes` (_default_ `false`) - determines if the result should include empty attributes
These two options are also applicable to `dia.Graph.toJSON()` method.
This PR also includes a new `util.objectDifference` function used to determine the difference between two provided objects.
https://docs.jointjs.com/api/dia/Cell/#tojson
```ts
cell.toJSON([opt])
```
Return a copy of …

feat(dia.Cell): new toJSON options

---

packages/joint-core/types/joint.d.ts

According to the source code, `dia.Element.size()` has the following three signatures:
- getter (no arguments) = `return this.get('size')`
- setter (two arguments, first argument is an object) = read `width` and `height` from first argument (if not present, get the missing value from the current `size` attribute), pass `width`, `height`, and second argument to `this.resize` as `width`, `height`, `opt`
- setter (three arguments) = `return this.resize(width, height, opt)`
```ts
element.size(): Size;
```
Return the current size of the element as an object with `width` and `height`.
```ts
element.size(
size: Partial<Size>,
opt?: Element.ResizeOptions
): this;
```
Change the size of the element with an object that specifies the new `width` and `height`. If a value is not provided for a …

types(dia.Element): fix size() signature

---

examples/tree-of-life/src/index.ts
packages/joint-core/demo/custom-shapes/src/custom-shapes.mjs
packages/joint-core/demo/puzzle/src/puzzle.js
packages/joint-core/demo/rough/src/rough.js
packages/joint-core/demo/shapes/src/standard.js
packages/joint-core/docs/demo/shapes/shapes.standard.js
packages/joint-core/src/dia/CellView.mjs
packages/joint-core/src/dia/attributes/connection.mjs
packages/joint-core/src/dia/attributes/defs.mjs
packages/joint-core/src/dia/attributes/index.mjs
packages/joint-core/src/dia/attributes/shape.mjs
packages/joint-core/src/dia/attributes/text.mjs
packages/joint-core/src/shapes/standard.mjs
packages/joint-core/test/jointjs/dia/attributes.js
packages/joint-core/test/ts/index.test.ts
packages/joint-core/types/joint.d.ts

If you currently set `sourceMarker` and later try to remove it by setting it to `null`, `marker-start` SVG attribute will not be removed from the DOM. This is a mechanism to ensure that the actual presentation attributes can be removed if necessary.
This PR also defines TypeScript for defining custom special attributes and fixes various examples where special attributes were used.
The `unset` callback for presentation attributes is called when an attribute is set to `null`.
- If there is no `unset` callback defined, an attribute with the same name as attribute definition is removed.
- Otherwise, it can be a **string** (an attribute to be removed from the DOM element), an **array of strings**, or a function that returns the aforementioned string or array.
- The callback accepts `(node, …

feat(dia.CellView): add unset() attribute callback

---

packages/joint-core/demo/custom-shapes/src/custom-shapes.mjs

Utilizing built-in Geometry method (`g.Point.fromPolar()`) to replace code from Stack Overflow.

chore(demo.custom-shapes): rewrite progress-data attribute using Geometry built-in methods

---

packages/joint-core/src/linkTools/Button.mjs
packages/joint-core/test/jointjs/dia/linkTools.js
packages/joint-core/test/ts/toolsView.test.ts
packages/joint-core/types/joint.d.ts

Allow the position of the link tool buttons to be dynamic.
For instance, based on the connection length:
```ts
new linkTools.Button({
// show button 20px from the target for short links
// and in the middle of the link for longer links
distance: (view) => view.getConnectionLength() < 100 ? -20 : '50%'
});
```

feat(linkTools.Button): allow distance to be defined via callback

---

packages/joint-core/src/elementTools/Control.mjs
packages/joint-core/test/jointjs/dia/elementTools.js
packages/joint-core/types/joint.d.ts

The current signature:
```ts
abstract class Control extends dia.ToolView {
protected getPosition(view: dia.ElementView): dia.Point;
protected setPosition(view: dia.ElementView, coordinates: g.Point): void;
protected resetPosition(view: dia.ElementView): void;
}
```
Is changed to:
```ts
abstract class Control extends dia.ToolView {
protected getPosition(view: dia.ElementView): dia.Point;
protected setPosition(view: dia.ElementView, coordinates: g.Point, evt: dia.Event): void;
protected resetPosition(view: dia.ElementView, evt: dia.Event): void;
}
```
This allows anyone to modify the behavior of the control tool based on a UI event.
_e.g. disable the resize tool from snapping to the grid when the user holds down the `Shift` key._

feat(elementTools.Control): add UI event to setPosition() and resetPosition() signature

---

packages/joint-core/src/dia/ElementView.mjs
packages/joint-core/test/jointjs/embedding.js
packages/joint-core/types/joint.d.ts

```ts
dia.ElementView.prototype.getTargetParentView(evt: dia.Event): dia.CellView | null;
```
The method returns a cell view (if any) that would become the parent of the currently dragged element view if the dragging were to finish immediately.
```ts
paper.on('element:pointermove', (elementView, evt) => {
console.log(elementView.getTargetParentView(evt));
});
// It can also be used while the user is dragging an element from the stencil
stencil.on('element:drag', (cloneView, evt) => {
console.log(cloneView.getTargetParentView(evt));
});
```

feat(dia.ElementView): add getTargetParentView() method

---

packages/joint-core/src/dia/attributes/eval.mjs
packages/joint-core/src/dia/attributes/text.mjs
packages/joint-core/src/elementTools/HoverConnect.mjs
packages/joint-core/src/layout/ports/port.mjs
packages/joint-core/src/linkTools/Button.mjs
packages/joint-core/src/util/calc.mjs
packages/joint-core/src/util/index.mjs
packages/joint-core/types/joint.d.ts

Add `isCalcExpression`, `evalCalcExpression` and `evalCalcFormula` functions to utilities.
```ts
isCalcExpression(value: any) => boolean
```
Check if the given value is a `calc()` expression.
e.g. `"calc(w + 100)"` is `true` and `"not a formula"` is `false`.
```ts
evalCalcExpression(expression: string, rect: g.PlainRect) => string;
```
Evaluate all `calc()` formulas in the given expression.
e.g. `"translate(calc(w + 10), 0)"` in a rect 100x100 will produce a string '"translate(110, 0)"'.
```ts
evalCalcFormula(formula: string, rect: g.PlainRect) => number;
```
Evaluate the given `calc()` formula.
e.g `w + 10` in context of a rectangle 100x100 will produce a number `110`.

feat(util): expose calc() expression API

---

packages/joint-core/src/dia/Cell.mjs
packages/joint-core/src/dia/Graph.mjs
packages/joint-core/test/jointjs/cell.js
packages/joint-core/test/jointjs/graph.js
packages/joint-core/types/joint.d.ts

Add `graph.transferCellEmbeds()` and `graph.transferCellConnectedLinks()`.
Change the `dia.Cell.embed` method to accept `opt.reparent`.
```ts
graph.transferCellEmbeds(sourceCell, targetCell [, opt]);
```
Transfer embedded cells of `sourceCell` to `targetCell`.
```ts
graph.transferCellConnectedLinks(sourceCell, targetCell [, opt]);
```
Transfer all the links connected to `sourceCell` to `targetCell`.
...
The `opt.reparent` option can be set to `true` to transfer the embedded cells from their current parent to the new parent.

feat(dia.Graph): add transferCellEmbeds() and transferCellConnectedLinks()

---

packages/joint-core/demo/archive/joint.dia.LegacyLinkView.js
packages/joint-core/demo/chess/src/chess.js
packages/joint-core/src/dia/CellView.mjs
packages/joint-core/src/dia/ElementView.mjs
packages/joint-core/src/dia/Graph.mjs
packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/src/g/rect.mjs
packages/joint-core/test/geometry/rect.js
packages/joint-core/test/jointjs/graph.js
packages/joint-core/test/jointjs/paper.js
packages/joint-core/types/geometry.d.ts
packages/joint-core/types/joint.d.ts

- **feat(dia.Paper):**  add methods to find cell/element/link views in paper
- add `findCellViewsAtPoint(), `findLinkViewsAtPoint()`, and `findElementViewsAtPoint()`
- add `findCellViewsInArea(), `findLinkViewsInArea()`, and `findElementViewsInArea()`
- deprecate `findViewsFromPoint()` and `findViewsInArea()
- **feat(dia.Graph):**  add methods to find cells/elements/links in graph
- add `findCellsAtPoint()`, `findLinksAtPoint()`, and `findElementsAtPoint()`
- add `findCellsInArea()`, `findLinksInArea()`, and `findElementsInArea()`
- add `findCellsUnderElement()`, `findLinksUnderElement()`, `findElementsUnderElement()`
- deprecate `findModelsFromPoint()` and `findModelsInArea()`
- **feat(dia.CellView):** add `isIntersecting()` method
- **feat(g.Rect):** add `strict` option to …

feat(dia.Paper):  add methods to find cell/element/link views in paper

---

packages/joint-layout-directed-graph/DirectedGraph.d.ts
packages/joint-layout-directed-graph/DirectedGraph.mjs
packages/joint-layout-directed-graph/test/index.js

The `fromGraphLib()` utility can now be used without providing the graph reference through context (this was an oversight during the conversion of `DirectedGraph` into a standalone package).
For backward compatibility, passing graph through context is still supported but is now deprecated. Instead, the graph should be provided via the `graph` option.

feat(layout.DirectedGraph): add `graph` option to fromGraphLib()

---

packages/joint-layout-directed-graph/DirectedGraph.d.ts

Rename `toGraphLibOptions` and `fromGraphLibOptions` to `ToGraphLibOptions` and `FromGraphLibOptions` (all interfaces in _JointJS_ start with a capital letter).
Deprecate the old names (keep them for backwards compatibility).

types(layout.DirectedGraph): capitalize interface names

---

CHANGELOG
examples/decorators/package.json
examples/dwdm/package.json
examples/fta-js/package.json
examples/isometric/package.json
examples/layout-directed-graph/package.json
examples/libavoid/package.json
examples/link-labels-ts/package.json
examples/list/package.json
examples/shapes-general/package.json
examples/tree-of-life/package.json
package.json
packages/joint-core/demo/custom-shapes/package.json
packages/joint-core/demo/elk/package.json
packages/joint-core/demo/rough/package.json
packages/joint-core/demo/tree-shake/package.json
packages/joint-core/demo/ts-demo/package.json
packages/joint-core/demo/vuejs/package.json
packages/joint-core/package.json
packages/joint-decorators/package.json
packages/joint-layout-directed-graph/package.json
packages/joint-shapes-general-tools/package.json
packages/joint-shapes-general/package.json

* **dia.Paper** - add methods to find cell/element/link views in paper (ca06b4e5dd8221644441f41698cfd2bd1c36cd6b)
* **dia.ElementView** - add `getTargetParentView()` method (0d29e703ae877815dc0092afb0418cbd2a5687e4)
* **dia.ElementView** - fix to prevent exception when position or size is not defined (3bead1c4fc50e3e54f958589da0829b16fa8d467)
* **dia.LinkView** - update tools when labels change (f5df2d1b6fad47aa55304c580cfd2f604c12ebf6)
* **dia.LinkView** - fix to invalidate the root node cache when labels change (6d12e652bbf133b5e6f85b3b4889218258604610)
* **dia.CellView** - expose special presentation attributes API (58df31d4c4c0ce198e36b10d591a004ea70f13fc)
* **dia.CellView** - add `isIntersecting()` method (ca06b4e5dd8221644441f41698cfd2bd1c36cd6b)
* **dia.Graph** - accept `toJSON()` …

Release v4.1.0

---

packages/joint-core/src/dia/ToolsView.mjs
packages/joint-core/test/jointjs/dia/linkTools.js

PR ensures that `update()` of tools is called after they are rendered.
```ts
paper.freeze();
const remove = new joint.linkTools.Vertices();
const toolsView = new joint.dia.ToolsView({ tools: [remove] });
linkView.addTools(toolsView);
linkView.hideTools();
paper.unfreeze();
// ASSERT: the tools are not rendered yet
linkView.showTools();
// ASSERT: tools are now rendered (previously an update was called without the tools being correctly rendered)

fix(dia.ToolsView): make sure tools are rendered before the first update

---

packages/joint-core/src/mvc/Listener.mjs

Due to its dependency on `Vectorizer`, the `mvc.Listener` cannot be initialized in environments without access to the DOM (e.g. [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API)). This PR removes that dependency.

refactor(mvc.Listener): drop Vectorizer dependency

---

packages/joint-core/src/mvc/Dom/methods.mjs

This change updates the `position()` method to use the `getComputedStyle()` function to accurately retrieve the `position` property of the currently checked parent element. This ensures the proper handling of style inheritance and computed values.
Fixes a bug introduced in #2852 by checking if the parent is statically positioned while retrieving the position in the `position()` method. This as a result led to incorrect positioning of the current view of the ui.Navigator plugin.

fix(mvc.Dom): use getComputedStyle for static position check for position method

---

packages/joint-core/src/dia/ElementView.mjs
packages/joint-core/types/joint.d.ts

This change enables customization of the snap-to-grid behavior, allowing for:  
- Snapping to the element's center (or to any point)
- Using key modifiers to adjust snapping behavior
```ts
import { dia, g } from '@joint/core';
const paper = new dia.Paper({
/* ... */
elementView: jdia.ElementView.extend({
snapToGrid: function(_evt, x, y) {
const gridSize = this.paper.options.gridSize;
const { width, height } = this.model.size();
// snap to the center of the element to the grid
const snapX = g.snapToGrid(x + width / 2, gridSize);
const snapY = g.snapToGrid(y + height / 2, gridSize);
return { x: snapX - width / 2, y: snapY - height / 2 };
}
})
});
```

refactor(dia.ElementView): extract snap-to-grid logic into dedicated method

---

packages/joint-core/demo/flowchart/index.js

Setting the vertices is redundant in the demo because the `rightAngle` router default settings does not take them into account.

chore: remove reduntant code from the flowchart example

---

packages/joint-layout-directed-graph/DirectedGraph.mjs
packages/joint-layout-directed-graph/test/index.js

[`packages/joint-layout-directed-graph/DirectedGraph.mjs`](diffhunk://#diff-4160b35b99723d64bcc0e9b589e88f2f5ce8d40317680232c1827c4532ff3668L176-R184): Modified the cluster resizing logic to filter out top-level clusters and apply the `fitToChildren` method in reverse-depth order, ensuring that clusters are resized starting from the deepest descendants.
[`packages/joint-layout-directed-graph/test/index.js`](diffhunk://#diff-d69c93ebe62fc85b15e75126feda906a15759059aac0a6fad3ebe4fbde437626R320-R356): Added a new test to verify that clusters are resized correctly. The test embeds multiple elements within each other, applies the layout, and checks that each parent element is resized to fit its children with the specified padding.
Refactor the existing solution, while maintaining the logic and …

refactor(DirectedGraph): utilize opt.deep for fitToChildren call when resizing clusters 

---

packages/joint-core/src/dia/Element.mjs
packages/joint-core/test/jointjs/elements.js
packages/joint-core/types/joint.d.ts

Provides two new options for `element.fitToChildren()` and `element.fitParent()` methods:
- `opt.filter` = provide a callback function that returns `true` when an element-type child should be included
- `opt.minRect` = provide an object with `x`, `y`, `width` and `height` which specifies a minimum rectangle that must be part of the bounding box after fitting (added via union with the fitting result)
Edge cases:
- `opt.padding` is not applied on top of `opt.minRect` because `opt.padding` only specifies padding that embedded elements must have from the bounding box after fitting and thus doesn't apply to empty space inside the minimal rectangle
- When used together with `opt.deep`, `opt.minRect` is only applied for the first iteration, but not for any other
- If the element has no filtered …

feat(dia.Element): add filter and minRect options to fitToChildren() and fitParent()

---

packages/joint-core/src/dia/HighlighterView.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js
packages/joint-core/types/joint.d.ts

This change introduces the ability to set the stacking order (`z-index`) for highlighters within the stacking context of `dia.CellView`. The `opt.z` controls whether a highlighter is inserted before or after other elements in the DOM hierarchy.
Update *layer* and *z* sections of the documentation to reflect the changes.
https://docs.jointjs.com/api/dia/HighlighterView/#options
**layer** - the stacking context of the highlighter. Applicable for [mountable](#mountable) highlighters only.
<table><tbody><tr><td>null</td><td>Render the highlighter within the dia.CellView, with its position determined by the provided z value. By default, the highlighter is rendered above the cell.</td></tr><tr><td>back</td><td>Render the highlighter behind all the cells.</td></tr><tr><td>front</td><td>Render …

feat(dia.HighlighterView): enable positioning of highlighter based on opt.z

---

packages/joint-layout-directed-graph/DirectedGraph.mjs

Fixes #2894 by checking that provided value is a number. Uses dagre defaults otherwise.
Also applies the same check to the `marginx` and `marginy` values. Uses `0` otherwise (dagre default).

fix(joint-layout-directed-graph): Accept 0 value for nodesep, edgesep, ranksep

---

packages/joint-layout-directed-graph/DirectedGraph.mjs
packages/joint-layout-directed-graph/test/index.js

The changes ensure that only the top-level clusters get resized if the glGraph has references to their children.
Added test for the scenario where the layout function is called with container elements without their children - the expected result is not resizing the containers, since the call to the function was made without the children.
PR #2886 introduced a bug in the filtering logic for clusters to be resized. The original condition, `glGraph.children(v).length > 0`, accounted for special cases where no children were provided for layouting. However, the current implementation does not handle these cases correctly.

fix(@joint/layout-directed-graph): refine top-level cluster filtering

---

packages/joint-core/src/anchors/index.mjs
packages/joint-core/test/jointjs/dia/anchors.js

Added support for _calc_ expressions when offsetting anchors (options `dx` and `dy`).
```ts
link.prop('source/anchor': {
name: 'topLeft',
args: {
dx: 'calc(w - 20)', // previously only a number or percentage
dy: 'calc(h - 20)'
}
});
```
Support added for the following anchors: `center`, `top`, `bottom`, `left`, `right`, `topLeft`, `topRight`, `bottomLeft`, `bottomRight`

feat(anchors): support for calc expressions in dx,dy options

---

packages/joint-vitest-plugin-mock-svg/mocks/index.ts
packages/joint-vitest-plugin-mock-svg/test/react/src/App.tsx

Add missing `getScreenCTM()` method to all `SVGGraphicsElements`.
The method is actually added to `SVGElement` protoype. It is because JSDOM `SVGGraphicsElement` does not encompass all SVG elements that might be needed, whereas `SVGElement` provides broader compatibility.

fix(vitest-plugin-mock-svg): mock getScreenCTM()

---

packages/joint-core/src/linkTools/Vertices.mjs

Fixes the blur logic of Vertices link tool when `redundancyRemoval: false`. We now call `blur()` as well as all appropriate `linkView` logic:
- stop the 'vertex-move' batch (and 'vertex-add', if relevant)
- `notifyPointerup()`
- `checkMouseleave()`
This brings the tool in line with other link tools when `redundancyRemoval: false`.

fix(linkTools/Vertices): call blur when redundancyRemoval: false

---

.travis.yml

Align node version we use with the node version used by Travis CI for running tests.

chore: upgrade node in travis to v22

---

packages/joint-core/src/dia/ports.mjs
packages/joint-core/test/jointjs/basic.js
packages/joint-core/types/joint.d.ts

Currently, port position arguments are read from top-level `args` port property, which is inconsistent with port groups and port labels (they both read those from `position.args` property).
This PR aligns the three - port's `position.args` are the source of truth for port position arguments. (To keep backwards compatibility, if there are no `position.args`, `args` are checked second.) For example:
```
g1.addPort({
position: {
args: {
dx: 20
}
},
attrs: {
circle: {
magnet: true,
stroke: '#31d0c6',
'stroke-width': 2,
fill: '#ffffff'
}
}
});
```

feat(dia.ports): port position args now provided inside position property

---

packages/joint-layout-directed-graph/DirectedGraph.d.ts
packages/joint-layout-directed-graph/DirectedGraph.mjs
packages/joint-layout-directed-graph/test/index.js

Supports `opt.clusterPadding: 'default'`, which applies default Dagre padding logic for clustered elements.
The option is only relevant when `opt.resizeClusters: true` (this was already the case when `opt.clusterPadding` is a number).

feat(layout-directed-graph): support clusterPadding: 'default'

---

packages/joint-vitest-plugin-mock-svg/mocks/index.ts
packages/joint-vitest-plugin-mock-svg/test/vue/src/App.vue

Refactors mock logic according to a fix that was necessary to make the mocks work in Jest (https://github.com/clientIO/joint-plus-tutorial-react/pull/15). Applied here for consistency and/or eventual merging of the two duplicate codebases (i.e. [mocks/index.ts](https://github.com/clientIO/joint/blob/5a7f9e9cae8dd92a982643117f2d76479901ba40/packages/joint-vitest-plugin-mock-svg/mocks/index.ts) vs [setupTests.ts](https://github.com/clientIO/joint-plus-tutorial-react/blob/6e5eb9ca2a4f99f43bcfc981c6aee7dfa8432bac/src/setupTests.ts)):
- The `fn().mockImplementation(() => SVGMatrix)` pattern (where `const SVGMatrix = ({...});`) is replaced by `fn().mockImplementation(createSVGMatrix)` (where `const createSVGMatrix = () => ({...});`).
Also adds a line to Vue test matching that added to React …

chore(joint-vitest-mock-svg): Fix mocks according to Jest

---

packages/joint-core/types/joint.d.ts

- Change `cleanNodesCache` ts to public - needed for `@joint/react`
- Add missing `cleanNodeCache` ts def -  needed for `@joint/react`
It's essential to be able to clear node cache from outside the view. For instance, after the element views are rendered asynchronously through **`React` portals.** (`@joint/react`).

chore(joint-core): update ts support

---

packages/joint-layout-directed-graph/DirectedGraph.d.ts
packages/joint-layout-directed-graph/DirectedGraph.mjs
packages/joint-layout-directed-graph/package.json
packages/joint-layout-directed-graph/test/index.js
yarn.lock

Expose `dagre` options `disableOptimalOrderHeuristic` and `customOrder` through the `DirectedGraph.layout()` function.

feat(layout-directed-graph): add `disableOptimalOrderHeuristic` and `customOrder` options

---

packages/joint-core/types/joint.d.ts

Separate the `options`  from `BreakTextFunction` into `BreakTextOptions` type.
Needed by `@joint/react` package.

type(util): refactor breakText function options for improved readability

---

packages/joint-core/src/anchors/index.mjs
packages/joint-core/src/cellTools/Boundary.mjs
packages/joint-core/src/cellTools/Control.mjs
packages/joint-core/src/connectionStrategies/index.mjs
packages/joint-core/src/dia/Cell.mjs
packages/joint-core/src/dia/Element.mjs
packages/joint-core/src/dia/Link.mjs
packages/joint-core/src/linkTools/Anchor.mjs
packages/joint-core/test/jointjs/elements.js
packages/joint-core/test/jointjs/links.js
packages/joint-core/types/joint.d.ts

Add a new `getCenter()` method as a counterpart to `getBBox()`. Previously, getting the center of an element required computing the full bounding box and then extracting the center, which involved creating a temporary `Rect` object subject to garbage collection. Since the center is frequently needed in calculations, this new method helps reduce memory usage slightly.
```ts
element.getCenter()
```
Returns the element center point (an instance of `g.Point`).
---
```ts
link.getCenter()
```
Returns the link center point (an instance of `g.Point`), which is the center of link's polyline bbox.

feat(dia.Cell): add getCenter() method

---

packages/joint-core/src/V/index.mjs

Make sure that `attributeName` and `repeatCount` attributes stay camel-case when set on the `<animation/>` element.

fix(Vectorizer): preserve camelCase in  'attributeName' and 'repeatCount' attribute names

---

packages/joint-core/src/dia/HighlighterView.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js

When a highlighter is used with an `SVGElement` as its [NodeSelector](https://docs.jointjs.com/api/dia/HighlighterView/#nodeselector), and that element is not part of the `CellView`, the node will not be highlighted. Instead, a `cell:highlighter:invalid` event is triggered—similar to what happens with a non-existent selector.
When a port is highlighted using an `SVGElement` selector and its attributes are updated, we need to make the highlighter invalid. This is because ports are re-rendered on each update, and the original `SVGElement` is removed from the DOM. The problem manifest during link reconnection, when the use set port attributes on `link:connect` event.
**Note:** This issue does not occur when using a JSON-based selector.

fix(dia.HighlighterView): prevent highlighting nodes outside cell view

---

packages/joint-core/src/V/index.mjs
packages/joint-core/test/vectorizer/vectorizer.js

If a line is missing any of its start/end coordinate attributes, it defaults to 0, but the `convertLineToPathData()` wasn't filling in zeros, but instead leaving missing attributes as the empty string, resulting in corrupt path data. So, default missing values to `0`.

fix(Vectorizer): handle implicit coordinates when converting lines to path data

---

packages/joint-core/src/dia/Cell.mjs
packages/joint-core/test/jointjs/cell.js

Fix array handling in the `Cell` constructor by always creating a deep copy of arrays rather than reusing the original instances.
Specifically, the problem occurred when the default values of the model attributes contained an array value.
```ts
const MyElement = dia.Element.define('MyElement', { attribute: [] });
const array = [1, 2];
const myElement = new MyElement({ attribute: array });
// assert: myElement.get('attrribute') !== array
const myElement2 = myElement.clone();
// assert: myElemen2.get('attrribute') !== myElement.get('attrribute')
```

fix(dia.Cell): always create a deep copy of arrays in constructor

---

packages/joint-core/src/dia/HighlighterView.mjs
packages/joint-core/test/jointjs/dia/HighlighterView.js

Previously, adding a Highlighter on a hidden subelement of an element (e.g. a hidden port) would permanently remove the highlighter from the document, so that it would not be shown again. Now, the highlighter is kept so that it can be shown again when the hidden subelement is shown again.
This change is required to fix a bug in the behavior of Record shapes in JointJS+, but is applicable across the board.

fix(dia.HighlighterView): unmount should not remove HighligterViews if not mounted yet

---

packages/joint-core/README.md

Currently, trying to install on an older Node version such as 18.x results in a failure while installing @joint/layout-directed-graph, which results in a failed installation overall.
This change simply adds a note above the recommendation regarding Yarn version to make a similar recommendation regarding Node version, for future installers.
Adds a one-liner to assist installers who are using older versions of Node.js
There is an indication on the required Yarn version, but not of the required Node version. Using an older version of Node (such as 18) results in the following error during install:
```
[@joint/layout-directed-graph]: Process started
[@joint/layout-directed-graph]: [!] SyntaxError: Unexpected token 'with'
[@joint/layout-directed-graph]:     at ESMLoader.moduleStrategy …
```

Add note regarding required Node version.

---

packages/joint-core/src/V/index.mjs
packages/joint-core/src/dia/attributes/text.mjs
packages/joint-core/test/jointjs/basic.js
packages/joint-core/test/jointjs/dia/attributes.js
packages/joint-core/types/vectorizer.d.ts

Mark the `V.sanitizeText()` method as `deprecated`. Hide the legacy functionality under `opt.useNoBreakSpace` for the `V.text()` method. And pass the `useNoBreakSpace` option for `text` attribute.
Fixes #2967
The conversion from `U+0020` to `U+00A0` was introduced for historical reasons but is no longer necessary and can be safely removed from the codebase.
___
*applies to*: `<text/>`
If set to `true`, all spaces (`U+0020`) in the text content will be replaced with a Unicode no-break space (`U+00A0`). The default value is `false`.
```ts
element.attr('label', {
text: '  Text',
useNoBreakSpace: true
});
```
___
Setting the `opt.useNoBreakSpace` to `true` will cause every standard space character (`U+0020`) in the provided `content` to be replaced with a Unicode no-break space (`U+00A0`).

feat: disable text sanitization by default

---

examples/libavoid/package.json
examples/libavoid/src/shared/avoid-router.js
examples/libavoid/webpack.config.js
yarn.lock

Update the libavoid package to the latest version, which introduces improvements in routing. This PR also introduces an event listener that handles resetting the graph.
Fixes #2914 
> When user creates more than a few links (around 7)* between 2 elements and then moves third element near the links the Paper freezes or breaks in non-deterministic way.

feat(examples): update libavoid example

---

packages/joint-core/types/joint.d.ts

Define the type of the second parameter of Element constructor, which allows you to define custom `portLayoutNamespace` and `portLabelLayoutNamespace`.
This fixes an oversight from #2991

types(dia.Element): describe element constructor options

---

packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/dia/Paper.js

Prevent exception when the `viewport` callback returned `false` for a generic `mvc.View` (because of missing `onDetach()` method.

fix(dia.Paper): fix for generic view detachment when `viewport()` callback returns false

---

packages/joint-core/types/joint.d.ts

Adds types for new MidSideAnchorArguments, missed as part of https://github.com/clientIO/joint/pull/2922

types(anchors): add types for new MidSideAnchorArguments

---

packages/joint-core/types/joint.d.ts

Fixes the type of properties which use `number | dia.Sides` as a type.
The `dia.Sides` type already contains `number | dia.SidesJSON`, so defining another `number` is not necessary.

types(dia): fix types which use dia.Sides

---

packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/dia/Paper.js
packages/joint-core/types/joint.d.ts

The PR adds the `isCellViewMounted()` method, which returns `true` if the specified `cell` is currently mounted.
```ts
isCellViewMounted(cellOrId: dia.Cell | dia.Cell.ID): boolean;
```
**Note:** Previously, the (non-public) `isViewMounted()` method accepted either a generic `mvc.View` or a model id. However, not all `mvc.View` instances are connected to a model. This pattern is not ideal, so this PR refactors it into two distinct methods:
- `protected isViewMounted()`, which takes any `view` instance or its `cid`
- `public isCellViewMounted()`, which accepts a `model` or its `id` 
Note that unmounting generic views is deprecated due to the new `cellVisibility` callback.

feat(dia.Paper): add `isCellViewMounted()` method

---

packages/joint-core/src/dia/LinkView.mjs
packages/joint-core/src/dia/Paper.mjs
packages/joint-core/test/jointjs/dia/Paper.js
packages/joint-core/types/joint.d.ts

The PR aims to simplify the API for cell visibility toggling.
Toggling visibility of cells is done via `updateCellsVisibility()` or `updateCellVisibility()`.
Toggling visibility of cells is done automatically by checking `cellVisibility()` callback periodically.
When `autoFreeze` option is enabled, one has to call `wakeUp()` to re-run the visibility checks.
The `updateCellsVisibility()` method can be used here, to synchronously show/hide cells e.g. before export to an image.
**feat(dia.Paper)** - add `updateCellVisibility(cell, opt)` to synchronously update visibility for a singe cell
```ts
updateCellVisibility(
cell: dia.Cell | dia.Cell.ID,
opt?: Paper.UpdateCellVisibilityOptions & Paper.UpdateViewOptions & Paper.RenderCallbackOptions
): void;
```
**feat(dia.Paper)** - …

feat(dia.Paper): add API to update cell visibility

---

packages/joint-core/types/joint.d.ts

Adds two fixes to `dia.Paper` typescript definitions:
- Recognizes that `Options.viewManagement` can be a boolean.
- Renames the `ScheduleCellVisibilityOptions` interface to `ScheduleCellsVisibilityUpdateOptions` to match the name of the method whose options it describes.
Brings types into alignment with the source code.

types(dia.Paper): boolean viewManagement, rename ScheduleCellVisibilityOptions

---

packages/joint-core/grunt/config/uglify.js
packages/joint-core/grunt/resources/banner.js
packages/joint-layout-directed-graph/rollup.config.mjs

Adds `'use strict';` at the beginning of minified files (in **@joint/core**, **@joint/layout-directed-graph**).
Additionally, slightly improves banner text formatting when it comes to newlines.
Our minification process removes all `'use strict';` statements from our code, which previously lead to subtle bugs (due to reuse of variable names in minified code). We are now adding one `'use strict';` statement explicitly at the beginning of each minified `.js` file.
- Old version:
```
/*! JointJS v4.1.3 (2025-02-04) - JavaScript diagramming library
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/
var g,V,Vectorizer;((t,e)=>
```
- New version:
``` …
```

fix: add 'use strict' for minified files
